import type { PaylasilanTemaConfig } from "@/components/temalar/paylasilan";

// Host -> paylaşımlı tema config'i. Yeni bir domain'i paylaşımlı temaya bağlamak
// için buraya birkaç satırlık bir entry eklemek yeterli; component kodu değişmez.
// NOT: her host aynı zamanda src/lib/siteler.ts (SiteIcerik + ticariSeoProfilleri)
// içinde de tanımlı olmalı, VE src/lib/hazirlanan-siteler.ts'te KAYITLI OLMAMALI
// (hazırlanan-siteler kontrolü page.tsx'te bu temadan önce çalışır ve varsa
// içeriği sessizce maskeler).
export const paylasilanTemaKonfigleri: Record<string, PaylasilanTemaConfig> = {
    // bozuyukplatform.com.tr eskiden bespoke temaydı (src/components/temalar/bozuyuk.tsx) —
    // sepetli platform hero fotoğrafı yanlış üründü, Ürünler sayfasında yinelenen slug
    // ve zayıf 3 kartlık katalog vardı, süreç bölümü dengesiz metin uzunluklarıyla
    // dağınık görünüyordu. Paylaşımlı temaya taşındı: gerçek 24 ürünlük katalog,
    // doğru fotoğraflar, DetayliRehber ve mobil menü otomatik geliyor.
    "bozuyukplatform.com.tr": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#2e3230",
            primaryLight: "#4a4e4a",
            accent: "#4a7c59",
            accentHover: "#3e6a4b",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#2e3230",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    // Pilot domain — logo 4 (yeşil, /public/media/logolar/4.png), Bolu'nun
    // orman/doğa kimliğiyle uyumlu accent rengi.
    "boluplatform.com": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/4.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00aa4f",
            accentHover: "#00923f",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.net": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/1.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#f1212b",
            accentHover: "#f1212b",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.xyz": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/2.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#516df3",
            accentHover: "#516df3",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.com.tr": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/3.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c3a100",
            accentHover: "#c3a100",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.com": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/5.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#81bf04",
            accentHover: "#81bf04",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.net": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#e16503",
            accentHover: "#e16503",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.xyz": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/7.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00b5bc",
            accentHover: "#00b5bc",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.net.tr": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/8.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc9e57",
            accentHover: "#cc9e57",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.org": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/9.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#974ada",
            accentHover: "#974ada",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.xyz": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/10.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#af8d03",
            accentHover: "#af8d03",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "canakkaleplatform.tr": {
        markaAdi: "Çanakkale Platform",
        logoUrl: "/media/logolar/11.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#3c5f98",
            accentHover: "#3c5f98",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "canakkaleplatform.xyz": {
        markaAdi: "Çanakkale Platform",
        logoUrl: "/media/logolar/12.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c4a404",
            accentHover: "#c4a404",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "kutahyaplatform.com.tr": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/13.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00a9b0",
            accentHover: "#00a9b0",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "kutahyaplatform.tr": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/14.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#9d5525",
            accentHover: "#9d5525",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "muglaplatform.com.tr": {
        markaAdi: "Muğla Platform",
        logoUrl: "/media/logolar/15.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#2b5790",
            accentHover: "#2b5790",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "muglaplatform.xyz": {
        markaAdi: "Muğla Platform",
        logoUrl: "/media/logolar/16.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#6b3088",
            accentHover: "#6b3088",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirmanlift.xyz": {
        markaAdi: "Eskişehir Manlift",
        logoUrl: "/media/logolar/17.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#93305d",
            accentHover: "#93305d",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirplatform.org": {
        markaAdi: "Eskişehir Platform",
        logoUrl: "/media/logolar/18.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "afyonplatform.com.tr": {
        markaAdi: "Afyon Platform",
        logoUrl: "/media/logolar/19.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cd1bd2",
            accentHover: "#cd1bd2",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaraeklemliplatform.com": {
        markaAdi: "Ankara Eklemli Platform",
        logoUrl: "/media/logolar/20.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bilecikplatform.com.tr": {
        markaAdi: "Bilecik Platform",
        logoUrl: "/media/logolar/21.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#d09d46",
            accentHover: "#d09d46",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmakasliplatform.xyz": {
        markaAdi: "İzmir Makaslı Platform",
        logoUrl: "/media/logolar/22.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#ffd940",
            accentHover: "#ffd940",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "denizliplatform.net": {
        markaAdi: "Denizli Platform",
        logoUrl: "/media/logolar/1.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#f1212b",
            accentHover: "#f1212b",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "usakplatform.com": {
        markaAdi: "Uşak Platform",
        logoUrl: "/media/logolar/2.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#516df3",
            accentHover: "#516df3",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "konyaplatform.net": {
        markaAdi: "Konya Platform",
        logoUrl: "/media/logolar/3.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c3a100",
            accentHover: "#c3a100",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ikincielplatform.net": {
        markaAdi: "İkinci El Platform",
        logoUrl: "/media/logolar/5.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#81bf04",
            accentHover: "#81bf04",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ikincielplatform.xyz": {
        markaAdi: "İkinci El Platform",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#e16503",
            accentHover: "#e16503",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankara-platform.com": {
        markaAdi: "Ankara Platform",
        logoUrl: "/media/logolar/7.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00b5bc",
            accentHover: "#00b5bc",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaramanlift.net": {
        markaAdi: "Ankara Manlift",
        logoUrl: "/media/logolar/8.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc9e57",
            accentHover: "#cc9e57",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaraplatform.net": {
        markaAdi: "Ankara Platform",
        logoUrl: "/media/logolar/9.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#974ada",
            accentHover: "#974ada",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bursamanlift.net": {
        markaAdi: "Bursa Manlift",
        logoUrl: "/media/logolar/10.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#af8d03",
            accentHover: "#af8d03",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bursamanliftkiralama.net": {
        markaAdi: "Bursa Manlift Kiralama",
        logoUrl: "/media/logolar/11.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#3c5f98",
            accentHover: "#3c5f98",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmir-man-lift.com": {
        markaAdi: "İzmir Man-Lift",
        logoUrl: "/media/logolar/12.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c4a404",
            accentHover: "#c4a404",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmir-manlift.net": {
        markaAdi: "İzmir Manlift",
        logoUrl: "/media/logolar/13.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00a9b0",
            accentHover: "#00a9b0",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmanliftkiralama.net": {
        markaAdi: "İzmir Manlift Kiralama",
        logoUrl: "/media/logolar/14.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#9d5525",
            accentHover: "#9d5525",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmanliftkiralama.org": {
        markaAdi: "İzmir Manlift Kiralama",
        logoUrl: "/media/logolar/15.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#2b5790",
            accentHover: "#2b5790",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirplatformkiralama.org": {
        markaAdi: "İzmir Platform Kiralama",
        logoUrl: "/media/logolar/16.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#6b3088",
            accentHover: "#6b3088",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirplatformskiralama.com": {
        markaAdi: "İzmir Platform Kiralama",
        logoUrl: "/media/logolar/17.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#93305d",
            accentHover: "#93305d",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirmanlift.net": {
        markaAdi: "Eskişehir Manlift",
        logoUrl: "/media/logolar/18.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirplatformkiralama.net": {
        markaAdi: "Eskişehir Platform Kiralama",
        logoUrl: "/media/logolar/19.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cd1bd2",
            accentHover: "#cd1bd2",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirvincplatform.com": {
        markaAdi: "Eskişehir Vinç Platform",
        logoUrl: "/media/logolar/20.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "manlifteskisehir.com": {
        markaAdi: "Manlift Eskişehir",
        logoUrl: "/media/logolar/21.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#d09d46",
            accentHover: "#d09d46",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
};
