import type { PaylasilanTemaConfig } from "@/components/temalar/paylasilan";

// Host -> paylaşımlı tema config'i. Yeni bir domain'i paylaşımlı temaya bağlamak
// için buraya birkaç satırlık bir entry eklemek yeterli; component kodu değişmez.
// NOT: her host aynı zamanda src/lib/siteler.ts (SiteIcerik + ticariSeoProfilleri)
// içinde de tanımlı olmalı, VE src/lib/hazirlanan-siteler.ts'te KAYITLI OLMAMALI
// (hazırlanan-siteler kontrolü page.tsx'te bu temadan önce çalışır ve varsa
// içeriği sessizce maskeler).
export const paylasilanTemaKonfigleri: Record<string, PaylasilanTemaConfig> = {
    // Bu 15 domain 2026-08-06'da eklendi: 5'i Cloudflare'de tamamen boştu (hiç DNS
    // kaydı yoktu), 10'u ise kullanıcı onayıyla mevcut yönlendirmelerinden (bkz.
    // domain portföyü raporu) ayrılıp kendi benzersiz içerikleriyle canlıya alındı.
    "afyonmanlift.com": {
        markaAdi: "Afyon Manlift",
        logoUrl: "/media/logolar/1.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#e16503", accentHover: "#c25703", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "afyonmanliftkiralama.net": {
        markaAdi: "Afyon Manlift Kiralama",
        logoUrl: "/media/logolar/2.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#00b5bc", accentHover: "#009a9f", accentFg: "#0a1525", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "afyonplatform.net": {
        markaAdi: "Afyon Platform",
        logoUrl: "/media/logolar/7.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#974ada", accentHover: "#8236c2", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "afyonplatformkiralama.com": {
        markaAdi: "Afyon Platform Kiralama",
        logoUrl: "/media/logolar/9.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#af8d03", accentHover: "#957703", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "izmir-forklift.com": {
        markaAdi: "İzmir Forklift",
        logoUrl: "/media/logolar/11.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#2b5790", accentHover: "#234873", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "izmirmakasliplatform.com.tr": {
        markaAdi: "İzmir Makaslı Platform",
        logoUrl: "/media/logolar/12.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#6b3088", accentHover: "#582871", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "izmirmakasliplatform.net.tr": {
        markaAdi: "İzmir Makaslı Platform",
        logoUrl: "/media/logolar/13.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#93305d", accentHover: "#7a284d", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkirala.net": {
        markaAdi: "Ankara Manlift Kirala",
        logoUrl: "/media/logolar/15.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#cc501a", accentHover: "#ad4315", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkirala.online": {
        markaAdi: "Bursa Manlift Kirala",
        logoUrl: "/media/logolar/17.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#516df3", accentHover: "#3a54e0", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkirala.store": {
        markaAdi: "Konya Manlift Kirala",
        logoUrl: "/media/logolar/20.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#c3a100", accentHover: "#a68800", accentFg: "#0a1525", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkirala.xyz": {
        markaAdi: "Denizli Manlift Kirala",
        logoUrl: "/media/logolar/4.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#81bf04", accentHover: "#6ca303", accentFg: "#0a1525", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkiralama.online": {
        markaAdi: "Kayseri Manlift Kiralama",
        logoUrl: "/media/logolar/3.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#9d5525", accentHover: "#84461e", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkiralama.org.tr": {
        markaAdi: "Gaziantep Manlift Kiralama",
        logoUrl: "/media/logolar/5.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#00a9b0", accentHover: "#008d93", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkiralama.site": {
        markaAdi: "Samsun Manlift Kiralama",
        logoUrl: "/media/logolar/8.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#3c5f98", accentHover: "#31507f", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "manliftkiralama.xyz": {
        markaAdi: "Adana Manlift Kiralama",
        logoUrl: "/media/logolar/10.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#cd1bd2", accentHover: "#ac16b0", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    // Aşağıdaki 10 domain eski 3. parti hosting'den (İsimtescil paylaşımlı hosting)
    // kuluçka-hub'a taşındı — bkz. siteler.ts'teki aynı bloktaki not.
    "afyonplatform.com": {
        markaAdi: "Afyon Platform",
        logoUrl: "/media/logolar/14.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#e16503", accentHover: "#c25703", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "amasyaplatform.com": {
        markaAdi: "Amasya Platform",
        logoUrl: "/media/logolar/16.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#81bf04", accentHover: "#6ca303", accentFg: "#0a1525", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "balikesirplatform.org": {
        markaAdi: "Balıkesir Platform",
        logoUrl: "/media/logolar/18.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#00b5bc", accentHover: "#009a9f", accentFg: "#0a1525", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "bilecikplatform.net": {
        markaAdi: "Bilecik Platform",
        logoUrl: "/media/logolar/20.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#974ada", accentHover: "#8236c2", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "bozuyukplatform.com": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/22.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#3c5f98", accentHover: "#31507f", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "bozuyukplatform.net": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/6.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#9d5525", accentHover: "#84461e", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "bursaeklemliplatform.net": {
        markaAdi: "Bursa Eklemli Platform",
        logoUrl: "/media/logolar/9.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#af8d03", accentHover: "#957703", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "eskisehirplatform.net": {
        markaAdi: "Eskişehir Platform",
        logoUrl: "/media/logolar/11.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#2b5790", accentHover: "#234873", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "istanbuleklemliplatform.com": {
        markaAdi: "İstanbul Eklemli Platform",
        logoUrl: "/media/logolar/12.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#6b3088", accentHover: "#582871", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    "kutahyaplatform.net": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/13.png",
        renkler: { primary: "#0a1525", primaryLight: "#16233a", accent: "#93305d", accentHover: "#7a284d", accentFg: "#ffffff", bg: "#ffffff", fg: "#0a1525", muted: "#6b7280", elevated: "#f3f4f6", border: "#e5e7eb" },
    },
    // plusplatform.com.tr — gerçek marka: kendi logosu ve gerçek ürün fotoğrafları
    // kullanılıyor (bkz. public/media/plusplatform/, eski siteden indirildi).
    // platformistanbul.net — İstanbul grubu taşıma planının pilot domain'i
    // (bkz. İstanbul Grubu Taşıma Planı). Gerçek logo eski repodan alındı,
    // 12 blog yazısı da (src/lib/blog.ts) aynı reponun gerçek içeriğinden
    // dönüştürüldü — jenerik şablon değil.
    // İstanbul grubu Faz 2 — kalan 4 domain (bkz. İstanbul Grubu Taşıma Planı).
    // Her biri kendi gerçek logosuyla (public/media/<host>/logo.png, eski repolardan
    // alındı) ve gerçek blog içeriğiyle (src/lib/blog.ts) taşındı.
    "istanbuldaplatform.com": {
        markaAdi: "Artı Platform İstanbul",
        logoUrl: "/media/istanbuldaplatform/logo.png",
        renkler: {
            primary: "#0f2e22",
            primaryLight: "#1f4a38",
            accent: "#1a9c63",
            accentHover: "#15804f",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0f2e22",
            muted: "#6b7280",
            elevated: "#f0faf5",
            border: "#e5e7eb",
        },
    },
    "istanbulplatforms.com": {
        markaAdi: "İstanbul Platforms",
        logoUrl: "/media/istanbulplatforms/logo.png",
        renkler: {
            primary: "#0a1e42",
            primaryLight: "#15316b",
            accent: "#1e40af",
            accentHover: "#1a3690",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1e42",
            muted: "#6b7280",
            elevated: "#eef2ff",
            border: "#e5e7eb",
        },
    },
    "istanbulplatformkiralama.net": {
        markaAdi: "İstanbul Platform Kiralama",
        logoUrl: "/media/istanbulplatformkiralama/logo.png",
        renkler: {
            primary: "#020c1b",
            primaryLight: "#0f2438",
            accent: "#ccff00",
            accentHover: "#b3e600",
            accentFg: "#020c1b",
            bg: "#ffffff",
            fg: "#020c1b",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "istanbul-platform.com": {
        markaAdi: "İstanbul Platform",
        logoUrl: "/media/istanbulplatform/logo.png",
        renkler: {
            primary: "#020c1b",
            primaryLight: "#0f2438",
            accent: "#ccff00",
            accentHover: "#b3e600",
            accentFg: "#020c1b",
            bg: "#ffffff",
            fg: "#020c1b",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "platformistanbul.net": {
        markaAdi: "Artı Platform İstanbul",
        logoUrl: "/media/platformistanbul/logo.png",
        renkler: {
            primary: "#1a1530",
            primaryLight: "#332a52",
            accent: "#7c3aed",
            accentHover: "#6d28d9",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#1a1530",
            muted: "#6b7280",
            elevated: "#f5f3ff",
            border: "#e5e7eb",
        },
    },
    "plusplatform.com.tr": {
        markaAdi: "PLUS Platform",
        logoUrl: "/media/plusplatform/logo.png",
        renkler: {
            primary: "#1a1a1a",
            primaryLight: "#3a3a3a",
            accent: "#c1272d",
            accentHover: "#a01f24",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#1a1a1a",
            muted: "#6b7280",
            elevated: "#f7f4f4",
            border: "#e5e7eb",
        },
        galeriGorselleri: [
            { src: "/media/plusplatform/thjz-8.jpg", alt: "PLUS THJZ-8 akülü makaslı platform" },
            { src: "/media/plusplatform/thjz-12-a.jpg", alt: "PLUS THJZ-12 akülü makaslı platform" },
            { src: "/media/plusplatform/thjz-14.jpg", alt: "PLUS THJZ-14 akülü makaslı platform" },
            { src: "/media/plusplatform/thjz.jpg", alt: "PLUS THJZ akülü makaslı platform serisi" },
        ],
    },
    // bozuyukplatform.com.tr eskiden bespoke temaydı (src/components/temalar/bozuyuk.tsx) —
    // sepetli platform hero fotoğrafı yanlış üründü, Ürünler sayfasında yinelenen slug
    // ve zayıf 3 kartlık katalog vardı, süreç bölümü dengesiz metin uzunluklarıyla
    // dağınık görünüyordu. Paylaşımlı temaya taşındı: gerçek 24 ürünlük katalog,
    // doğru fotoğraflar, DetayliRehber ve mobil menü otomatik geliyor.
    "bozuyukplatform.com.tr": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#2e3230",
            primaryLight: "#4a4e4a",
            accent: "#4a7c59",
            accentHover: "#3e6a4b",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#2e3230",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    // Aşağıdaki 7 domain de bozuyuk ile aynı sebeple (sepetli/kamyon üstü platform
    // hero fotoğrafı, Ürünler sayfasında yinelenen slug + 3 kartlık zayıf katalog,
    // dengesiz metin sütunları) bespoke temadan paylaşımlı temaya taşındı.
    "aydinplatform.net": {
        markaAdi: "Aydın Platform",
        logoUrl: "/media/logolar/8.png",
        renkler: {
            primary: "#0A1525",
            primaryLight: "#16233a",
            accent: "#FBBF24",
            accentHover: "#e5ac16",
            accentFg: "#0A1525",
            bg: "#ffffff",
            fg: "#0A1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bilecikplatform.com": {
        markaAdi: "Bilecik Platform",
        logoUrl: "/media/logolar/10.png",
        renkler: {
            primary: "#3a302a",
            primaryLight: "#605850",
            accent: "#c2652a",
            accentHover: "#a8531f",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#3a302a",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "canakkaleplatform.com": {
        markaAdi: "Çanakkale Platform",
        logoUrl: "/media/logolar/14.png",
        renkler: {
            primary: "#1A1C1E",
            primaryLight: "#3a3d40",
            accent: "#ed1c24",
            accentHover: "#c8151c",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#1A1C1E",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eklemliplatform.com.tr": {
        markaAdi: "Eklemli Platform",
        logoUrl: "/media/logolar/16.png",
        renkler: {
            primary: "#191c1e",
            primaryLight: "#3a3d40",
            accent: "#3151eb",
            accentHover: "#2740c4",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#191c1e",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "kutahyaplatform.com": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/18.png",
        renkler: {
            primary: "#020617",
            primaryLight: "#1e293b",
            accent: "#1D4ED8",
            accentHover: "#1a41b8",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#020617",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirforkliftkiralama.net": {
        markaAdi: "İzmir Forklift Kiralama",
        logoUrl: "/media/logolar/3.png",
        renkler: {
            primary: "#121c2a",
            primaryLight: "#2a3a4d",
            accent: "#f68b1e",
            accentHover: "#d9760f",
            accentFg: "#121c2a",
            bg: "#ffffff",
            fg: "#121c2a",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "manisaforklift.com": {
        markaAdi: "Manisa Forklift",
        logoUrl: "/media/logolar/5.png",
        renkler: {
            primary: "#191c1e",
            primaryLight: "#3a3d40",
            accent: "#FBBF24",
            accentHover: "#e5ac16",
            accentFg: "#191c1e",
            bg: "#ffffff",
            fg: "#191c1e",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "platformmanisa.com": {
        markaAdi: "Platform Manisa",
        logoUrl: "/media/logolar/19.png",
        renkler: {
            primary: "#020617",
            primaryLight: "#1E293B",
            accent: "#b8c4ff",
            accentHover: "#9fb0ff",
            accentFg: "#020617",
            bg: "#ffffff",
            fg: "#020617",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    // Pilot domain — logo 4 (yeşil, /public/media/logolar/4.png), Bolu'nun
    // orman/doğa kimliğiyle uyumlu accent rengi.
    "boluplatform.com": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/4.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00aa4f",
            accentHover: "#00923f",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.net": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/1.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#f1212b",
            accentHover: "#f1212b",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.xyz": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/2.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#516df3",
            accentHover: "#516df3",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "boluplatform.com.tr": {
        markaAdi: "Bolu Platform",
        logoUrl: "/media/logolar/3.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c3a100",
            accentHover: "#c3a100",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.com": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/5.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#81bf04",
            accentHover: "#81bf04",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.net": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#e16503",
            accentHover: "#e16503",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukmanlift.xyz": {
        markaAdi: "Bozüyük Manlift",
        logoUrl: "/media/logolar/7.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00b5bc",
            accentHover: "#00b5bc",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.net.tr": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/8.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc9e57",
            accentHover: "#cc9e57",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.org": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/9.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#974ada",
            accentHover: "#974ada",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bozuyukplatform.xyz": {
        markaAdi: "Bozüyük Platform",
        logoUrl: "/media/logolar/10.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#af8d03",
            accentHover: "#af8d03",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "canakkaleplatform.tr": {
        markaAdi: "Çanakkale Platform",
        logoUrl: "/media/logolar/11.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#3c5f98",
            accentHover: "#3c5f98",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "canakkaleplatform.xyz": {
        markaAdi: "Çanakkale Platform",
        logoUrl: "/media/logolar/12.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c4a404",
            accentHover: "#c4a404",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "kutahyaplatform.com.tr": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/13.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00a9b0",
            accentHover: "#00a9b0",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "kutahyaplatform.tr": {
        markaAdi: "Kütahya Platform",
        logoUrl: "/media/logolar/14.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#9d5525",
            accentHover: "#9d5525",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "muglaplatform.com.tr": {
        markaAdi: "Muğla Platform",
        logoUrl: "/media/logolar/15.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#2b5790",
            accentHover: "#2b5790",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "muglaplatform.xyz": {
        markaAdi: "Muğla Platform",
        logoUrl: "/media/logolar/16.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#6b3088",
            accentHover: "#6b3088",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirmanlift.xyz": {
        markaAdi: "Eskişehir Manlift",
        logoUrl: "/media/logolar/17.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#93305d",
            accentHover: "#93305d",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirplatform.org": {
        markaAdi: "Eskişehir Platform",
        logoUrl: "/media/logolar/18.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "afyonplatform.com.tr": {
        markaAdi: "Afyon Platform",
        logoUrl: "/media/logolar/19.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cd1bd2",
            accentHover: "#cd1bd2",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaraeklemliplatform.com": {
        markaAdi: "Ankara Eklemli Platform",
        logoUrl: "/media/logolar/20.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bilecikplatform.com.tr": {
        markaAdi: "Bilecik Platform",
        logoUrl: "/media/logolar/21.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#d09d46",
            accentHover: "#d09d46",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmakasliplatform.xyz": {
        markaAdi: "İzmir Makaslı Platform",
        logoUrl: "/media/logolar/22.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#ffd940",
            accentHover: "#ffd940",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "denizliplatform.net": {
        markaAdi: "Denizli Platform",
        logoUrl: "/media/logolar/1.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#f1212b",
            accentHover: "#f1212b",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "usakplatform.com": {
        markaAdi: "Uşak Platform",
        logoUrl: "/media/logolar/2.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#516df3",
            accentHover: "#516df3",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "konyaplatform.net": {
        markaAdi: "Konya Platform",
        logoUrl: "/media/logolar/3.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c3a100",
            accentHover: "#c3a100",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ikincielplatform.net": {
        markaAdi: "İkinci El Platform",
        logoUrl: "/media/logolar/5.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#81bf04",
            accentHover: "#81bf04",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ikincielplatform.xyz": {
        markaAdi: "İkinci El Platform",
        logoUrl: "/media/logolar/6.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#e16503",
            accentHover: "#e16503",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankara-platform.com": {
        markaAdi: "Ankara Platform",
        logoUrl: "/media/logolar/7.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00b5bc",
            accentHover: "#00b5bc",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaramanlift.net": {
        markaAdi: "Ankara Manlift",
        logoUrl: "/media/logolar/8.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc9e57",
            accentHover: "#cc9e57",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "ankaraplatform.net": {
        markaAdi: "Ankara Platform",
        logoUrl: "/media/logolar/9.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#974ada",
            accentHover: "#974ada",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bursamanlift.net": {
        markaAdi: "Bursa Manlift",
        logoUrl: "/media/logolar/10.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#af8d03",
            accentHover: "#af8d03",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "bursamanliftkiralama.net": {
        markaAdi: "Bursa Manlift Kiralama",
        logoUrl: "/media/logolar/11.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#3c5f98",
            accentHover: "#3c5f98",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmir-man-lift.com": {
        markaAdi: "İzmir Man-Lift",
        logoUrl: "/media/logolar/12.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#c4a404",
            accentHover: "#c4a404",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmir-manlift.net": {
        markaAdi: "İzmir Manlift",
        logoUrl: "/media/logolar/13.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#00a9b0",
            accentHover: "#00a9b0",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmanliftkiralama.net": {
        markaAdi: "İzmir Manlift Kiralama",
        logoUrl: "/media/logolar/14.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#9d5525",
            accentHover: "#9d5525",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirmanliftkiralama.org": {
        markaAdi: "İzmir Manlift Kiralama",
        logoUrl: "/media/logolar/15.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#2b5790",
            accentHover: "#2b5790",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirplatformkiralama.org": {
        markaAdi: "İzmir Platform Kiralama",
        logoUrl: "/media/logolar/16.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#6b3088",
            accentHover: "#6b3088",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "izmirplatformskiralama.com": {
        markaAdi: "İzmir Platform Kiralama",
        logoUrl: "/media/logolar/17.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#93305d",
            accentHover: "#93305d",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirmanlift.net": {
        markaAdi: "Eskişehir Manlift",
        logoUrl: "/media/logolar/18.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirplatformkiralama.net": {
        markaAdi: "Eskişehir Platform Kiralama",
        logoUrl: "/media/logolar/19.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cd1bd2",
            accentHover: "#cd1bd2",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "eskisehirvincplatform.com": {
        markaAdi: "Eskişehir Vinç Platform",
        logoUrl: "/media/logolar/20.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#cc501a",
            accentHover: "#cc501a",
            accentFg: "#ffffff",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
    "manlifteskisehir.com": {
        markaAdi: "Manlift Eskişehir",
        logoUrl: "/media/logolar/21.png",
        renkler: {
            primary: "#0a1525",
            primaryLight: "#16233a",
            accent: "#d09d46",
            accentHover: "#d09d46",
            accentFg: "#0a1525",
            bg: "#ffffff",
            fg: "#0a1525",
            muted: "#6b7280",
            elevated: "#f3f4f6",
            border: "#e5e7eb",
        },
    },
};
