export interface SiteIcerik {
    host: string;
    gaId: string;
    baslik: string;
    aciklama: string;
    h1: string;
    paragraflar: string[];
    hizmetler: string[];
    anaSite: { ad: string; url: string };
    bolge: string;
    telefon: string;
    telefonGosterim: string;
    eposta: string;
    uzmanlik: string;
    kategori?: "kiralama" | "egitim" | "rehber";
    bolumler?: { baslik: string; href: string }[];
}

export const siteler: SiteIcerik[] = [
    {
        host: "eklemliplatform.com.tr",
        gaId: "G-CFM36MYGHJ",
        baslik: "Eklemli Platform Kiralama | Makine Seçimi ve Teklif",
        aciklama: "Eklemli platform kiralama için çalışma yüksekliği, yatay erişim, zemin ve süreye göre makine seçimi ve yazılı teklif süreci.",
        h1: "Eklemli Platform Kiralama",
        paragraflar: [
            "Eklemli (akrobat) platformlar, düz teleskopik bomların ulaşamadığı noktalara \"kırılan kol\" yapısıyla erişir: çatı arkaları, cephe girintileri, ağaç ve tesisat üzerinden aşarak çalışma gerektiren her nokta.",
            "Makine seçimi; çalışma yüksekliği, yatay erişim, zemin taşıma kapasitesi, iç veya dış mekân koşulu ve kiralama süresi birlikte değerlendirilerek yapılır. Yakıt tipi, operatör ve nakliye seçenekleri stok ve proje koşullarına göre yazılı teklifte netleştirilir.",
            "Çalışma alanının fotoğrafını, hedef yüksekliği ve erişim engellerini paylaşın; uygun bom sınıfı, teslimat planı ve maliyet kalemleri teyit edildikten sonra teklif oluşturulsun.",
        ],
        hizmetler: ["Elektrikli eklemli platform seçenekleri", "Dizel eklemli platform seçenekleri", "Yüksek erişim bom sınıfı planlaması", "Operatör ve nakliye seçeneği", "Saha bilgisine göre bom tipi danışmanlığı"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Türkiye geneli",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "engelli erişim gerektiren açık ve kapalı çalışma sahaları",
    },
    {
        host: "bandirmamanlift.net",
        gaId: "G-LDY8ZP140T",
        baslik: "Bandırma Manlift Kiralama | Bölgesel Teklif",
        aciklama: "Bandırma, Erdek, Gönen ve Biga hattında manlift kiralama için makaslı ve bomlu platform seçimi, nakliye planı ve yazılı teklif.",
        h1: "Bandırma Manlift Kiralama",
        paragraflar: [
            "Bandırma ve çevresindeki manlift taleplerinde teslimat noktası, makine sınıfı ve kiralama tarihine göre bölgesel uygunluk kontrol edilir.",
            "Liman lojistiği, fabrika bakımları, tersane işleri ve enerji tesisleri — Bandırma'nın sanayi dokusuna uygun makas ve bomlu platform seçeneklerini günlük veya proje bazlı kiralayabilirsiniz.",
            "Operatör, makine evrakı ve nakliye gereksinimleri teklif öncesinde ayrı ayrı teyit edilir. Çalışma yüksekliği, zemin, tarih ve saha giriş koşulları yazılı planın temelini oluşturur.",
        ],
        hizmetler: ["Makaslı platform kiralama (8-22 m)", "Bomlu platform kiralama (16-43 m)", "Liman ve tersane çalışmalarına uygun ekipman", "Günlük ve proje bazlı kiralama", "Nakliye ve İSG evrak organizasyonu"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Bandırma, Erdek, Gönen, Biga",
        telefon: "+905331728943",
        telefonGosterim: "0533 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "liman, tersane, enerji ve fabrika bakım sahaları",
    },
    {
        host: "izmirforkliftkiralama.net",
        gaId: "G-E24F8SWEFE",
        baslik: "İzmir Forklift Kiralama | Günlük, Aylık, Operatörlü",
        aciklama: "İzmir'de forklift kiralama için yük ağırlığı, yük merkezi, kaldırma yüksekliği, zemin ve çalışma süresine göre kapasite seçimi ve teklif.",
        h1: "İzmir Forklift Kiralama",
        paragraflar: [
            "Kemalpaşa, Torbalı, Çiğli ve Aliağa dahil İzmir taleplerinde doğru forklift; yük ağırlığı, yük merkezi, kaldırma yüksekliği, koridor genişliği ve zemin koşuluna göre seçilir.",
            "Dizel, LPG, elektrikli ve triplex seçeneklerin kapasite, ataşman, operatör ve süre uygunluğu güncel stok üzerinden kontrol edilir. Periyodik kontrol ve saha giriş belgeleri sözleşme öncesinde teyit edilir.",
            "Teslimat tarihi ve nakliye bedeli, makine uygunluğu ile mesafe doğrulandıktan sonra yazılı teklifte belirtilir.",
        ],
        hizmetler: ["1,5-3 ton elektrikli forkliftler (depo içi)", "3-5 ton dizel/LPG forkliftler", "7-10 ton ağır hizmet forkliftleri", "Operatörlü saatlik yükleme-boşaltma", "Aylık sözleşmeli uzun dönem kiralama"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "İzmir ve çevresi",
        telefon: "+905321728943",
        telefonGosterim: "0532 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "depo, üretim ve yükleme sahalarında forklift seçimi",
    },
    {
        host: "kutahyaplatform.com",
        gaId: "G-6C9FTW6S1G",
        baslik: "Kütahya Platform Kiralama | Seramik Sanayisine Çözüm",
        aciklama: "Kütahya ve ilçelerinde platform kiralama için seramik tesisi, depo ve bakım işlerine uygun makine seçimi ile sevkiyat teklifi.",
        h1: "Kütahya Platform Kiralama",
        paragraflar: [
            "Kütahya ve ilçelerinde makaslı ve bomlu platform kiralama. Seramik fabrikaları, depo raf sistemleri, cam ve çini atölyeleri ile kamu binalarının bakım işlerinde; 8-32 metre aralığında doğru platformu proje sürenize göre kiralıyoruz.",
            "Kütahya sevkiyatı; istenen makine, tarih, adres ve nakliye uygunluğu birlikte kontrol edilerek planlanır.",
            "İç mekân için elektrikli, açık saha için dizel seçenekler değerlendirilir; nakliye ve gerekli evrakların kapsamı yazılı teklifte netleştirilir.",
        ],
        hizmetler: ["Makaslı platformlar (8-18 m, elektrikli/dizel)", "Bomlu platformlar (16-32 m)", "Fabrika içi hassas zemin çözümleri", "Proje süresine göre esnek kiralama", "Aynı gün sevkiyat planlaması"],
        anaSite: { ad: "Eskişehir Platform", url: "https://eskisehirplatform.com" },
        bolge: "Kütahya ve ilçeleri",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "seramik üretimi, depo ve tesis bakım çalışmaları",
    },
    {
        host: "aydinplatform.net",
        gaId: "G-ZHS202Q2CZ",
        baslik: "Aydın Platform Kiralama | Efeler, Nazilli, Söke Hattı",
        aciklama: "Aydın genelinde platform kiralama için tesis, depo, otel ve inşaat işlerine uygun makine seçimi, sevkiyat planı ve teklif.",
        h1: "Aydın Platform Kiralama",
        paragraflar: [
            "Aydın merkez, Efeler, Nazilli, Söke ve Kuşadası hattında makaslı ve bomlu platform kiralama hizmeti veriyoruz. Jeotermal enerji tesisleri, zeytin ve incir işleme sanayii, oteller ve inşaat projeleri için 8-32 metre aralığında doğru makineyi seçiyoruz.",
            "Aydın, Kuşadası ve Didim sevkiyatları istenen makine sınıfı, tarih ve nakliye uygunluğuna göre planlanır; dönemsel kiralama şartları teklif sırasında belirlenir.",
            "Çalışma yüksekliği, yatay erişim, zemin, süre ve adres bilgilerini iletin; uygunluk kontrolünden sonra yazılı teklif hazırlansın.",
        ],
        hizmetler: ["Makaslı platformlar (8-18 m, elektrikli/dizel)", "Bomlu platformlar (16-32 m)", "Otel ve tesis bakımlarına dönemsel kiralama", "Tarım sanayii depo çalışmaları", "Aynı gün sevkiyat planlaması"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Aydın, Efeler, Nazilli, Söke, Kuşadası",
        telefon: "+905321728943",
        telefonGosterim: "0532 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "otel, enerji, tarım sanayisi ve tesis bakım işleri",
    },
    {
        host: "bilecikplatform.com",
        gaId: "G-W503GFYREQ",
        baslik: "Bilecik Platform Kiralama | Makine ve Sevkiyat Planı",
        aciklama: "Bilecik ve Bozüyük'te platform kiralama için seramik, metal ve depo çalışmalarına uygun makine seçimi ve sevkiyat teklifi.",
        h1: "Bilecik Platform Kiralama",
        paragraflar: [
            "Bilecik merkez, Bozüyük, Osmaneli ve Söğüt hattında makaslı ve bomlu platform kiralama. Seramik fabrikaları, metal işleme tesisleri ve depo projelerinde 8-32 metre aralığında çalışıyoruz.",
            "Bilecik sevkiyatı; güncel makine uygunluğu, teslimat adresi ve talep tarihine göre planlanır. Günlük veya daha uzun kiralama seçenekleri proje koşullarına göre fiyatlandırılır.",
            "Elektrikli modeller iç mekân, dizel modeller açık saha için değerlendirilir; nakliye ve gerekli evrak kapsamı sözleşmede belirtilir.",
        ],
        hizmetler: ["Makaslı platformlar (8-18 m)", "Bomlu platformlar (16-32 m)", "Fabrika bakım duruşlarına günlük kiralama", "Depo ve raf sistemi kurulum çalışmaları", "Nakliye ve İSG evrak organizasyonu"],
        anaSite: { ad: "Eskişehir Platform", url: "https://eskisehirplatform.com" },
        bolge: "Bilecik, Bozüyük, Osmaneli, Söğüt",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "seramik, metal işleme ve depo projeleri",
    },
    {
        host: "bozuyukplatform.com.tr",
        gaId: "G-80XK5R3BN2",
        baslik: "Bozüyük Platform Kiralama | OSB İçin Teklif",
        aciklama: "Bozüyük OSB ve çevresinde platform kiralama için seramik, cam ve lojistik tesislerine uygun makine seçimi ve sevkiyat planı.",
        h1: "Bozüyük Platform Kiralama",
        paragraflar: [
            "Bozüyük Organize Sanayi Bölgesi ve çevresindeki taleplerde seramik, cam ve lojistik tesislerinin bakım, raf ve aydınlatma işleri için makaslı veya bomlu platform seçimi yapılır.",
            "Teslimat zamanı; makine sınıfı, güncel uygunluk, adres ve saha giriş koşulları doğrulandıktan sonra belirlenir.",
            "Çalışma yüksekliği, yatay erişim ve zemin bilgisi üzerinden makine sınıfı değerlendirilir; kapasite ve ücret yazılı teklifte teyit edilir.",
        ],
        hizmetler: ["Makaslı platform seçenekleri", "Bomlu platform seçenekleri", "OSB saha koşulu değerlendirmesi", "Günlük ve proje bazlı teklif", "Makine ve nakliye planlaması"],
        anaSite: { ad: "Eskişehir Platform", url: "https://eskisehirplatform.com" },
        bolge: "Bozüyük OSB ve çevresi",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "OSB içi seramik, cam ve lojistik tesisleri",
    },
    {
        host: "canakkaleplatform.com",
        gaId: "G-SKXSE7ZCN5",
        baslik: "Çanakkale Platform Kiralama | Biga ve Merkeze Teslim",
        aciklama: "Çanakkale, Biga ve Çan hattında 8-32 m makaslı ve bomlu platform kiralama. Enerji santralleri, seramik ve gıda tesislerine uygun ekipman.",
        h1: "Çanakkale Platform Kiralama",
        paragraflar: [
            "Çanakkale merkez, Biga, Çan ve Gelibolu hattındaki enerji, metal, seramik ve inşaat işleri için makaslı veya bomlu platform sınıfı saha koşullarına göre değerlendirilir.",
            "Çanakkale sevkiyat günü; makine uygunluğu, çıkış noktası, feribot veya kara yolu planı ve teslimat adresi teyit edildikten sonra belirlenir.",
            "Rüzgâr santrali ve liman gibi özel sahalarda istenen makine evrakı, operatör yeterliliği ve giriş prosedürü teklif öncesinde karşılıklı doğrulanır.",
        ],
        hizmetler: ["Makaslı platformlar (8-18 m)", "Bomlu platformlar (16-32 m)", "Enerji santrali bakım çalışmaları", "Proje bazlı sahada konuşlu kiralama", "Belgeli operatör desteği"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Çanakkale, Biga, Çan, Gelibolu",
        telefon: "+905321728943",
        telefonGosterim: "0532 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "enerji, liman, metal ve seramik sahaları",
    },
    {
        host: "platformmanisa.com",
        gaId: "G-BKS6Y4X2JD",
        baslik: "Manisa Platform Kiralama | OSB ve İlçeler",
        aciklama: "Manisa OSB, Turgutlu, Salihli ve Akhisar'da platform kiralama için makine seçimi, saha koşulu değerlendirmesi ve sevkiyat teklifi.",
        h1: "Manisa Platform Kiralama",
        paragraflar: [
            "Manisa Organize Sanayi Bölgesi, Turgutlu, Salihli ve Akhisar hattında makaslı ve bomlu platform kiralama. Elektronik fabrikaları, gıda işleme tesisleri ve lojistik depoların yüksekte çalışma ihtiyaçlarında 8-32 metre aralığında hizmet veriyoruz.",
            "Manisa sevkiyatı ve varsa vardiya dışı teslimat talebi, makine ile nakliye uygunluğu teyit edildikten sonra yazılı plana bağlanır.",
            "Temiz üretim alanları için elektrikli, açık saha için dizel seçenekler değerlendirilir; kapasite seçimi zemin ve erişim bilgisine göre yapılır.",
        ],
        hizmetler: ["Elektrikli ve dizel makaslı seçenekleri", "Bomlu platform seçenekleri", "OSB teslimat planlaması", "İç ve dış mekân makine seçimi", "Kapasite danışmanlığı"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Manisa OSB, Turgutlu, Salihli, Akhisar",
        telefon: "+905321728943",
        telefonGosterim: "0532 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "OSB üretim tesisleri, depo ve bakım operasyonları",
    },
    {
        host: "manisaforklift.com",
        gaId: "G-754SNQKTY7",
        baslik: "Manisa Forklift Kiralama | OSB İçi Saatlik ve Aylık Kiralama",
        aciklama: "Manisa'da forklift kiralama için yük ağırlığı, yük merkezi, kaldırma yüksekliği, zemin ve süreye göre kapasite seçimi ve teklif.",
        h1: "Manisa Forklift Kiralama",
        paragraflar: [
            "Manisa OSB, Turgutlu ve Akhisar taleplerinde forklift kapasitesi; en ağır yük, yük merkezi, kaldırma yüksekliği, koridor ve zemin bilgisine göre belirlenir.",
            "Kapalı üretim alanları için elektrikli ve triplex, açık saha ile rampa işleri için dizel veya LPG seçeneklerinin uygunluğu güncel stok üzerinden kontrol edilir.",
            "Makine bakım kaydı, periyodik kontrol, operatör ve teslimat koşulları talebe göre incelenir ve sözleşme öncesinde yazılı olarak teyit edilir.",
        ],
        hizmetler: ["1,5-3 ton elektrikli forkliftler (depo içi)", "3-5 ton dizel/LPG forkliftler", "7-10 ton ağır hizmet forkliftleri", "Saatlik yükleme-boşaltma operasyonu", "Aylık sözleşmeli tedarik"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Manisa OSB, Turgutlu, Akhisar",
        telefon: "+905321728943",
        telefonGosterim: "0532 172 89 43",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "yükleme, depo ve üretim hattı forklift operasyonları",
    },
    {
        host: "yuksektecalismarehberi.com",
        gaId: "G-QG5XZ2JHQQ",
        baslik: "Yüksekte Çalışma Rehberi | Platform Seçimi, İSG ve Mevzuat",
        aciklama: "Yüksekte güvenli çalışma rehberi: makaslı/bomlu platform ve telehandler seçimi, İSG mevzuatı, operatör belgeleri ve pratik kontrol listeleri.",
        h1: "Yüksekte Çalışma Rehberi",
        paragraflar: [
            "Bu rehber; şantiye şefleri, bakım mühendisleri ve İSG uzmanları için yüksekte çalışma ekipmanı seçimini sadeleştirir: hangi işte makaslı platform, hangi işte eklemli veya teleskopik bom, hangi işte telehandler doğru tercihtir — gerekçeleriyle anlatıyoruz.",
            "İçerik yol haritamız: platform tipi seçim rehberi, telehandler ile bomlu platform karşılaştırması, 6331 sayılı İş Sağlığı ve Güvenliği Kanunu kapsamında yüksekte çalışma yükümlülükleri, operatör belgelendirme süreçleri ve iş öncesi kontrol listeleri.",
            "Rehber içerikleri sahada makine kiralayan ve kullanan ekiplerin gerçek sorularından derlenmektedir; yeni bölümler yayınlandıkça bu sayfadan duyurulur.",
        ],
        hizmetler: ["Platform tipi seçim rehberi (makaslı / eklemli / teleskopik)", "Telehandler mi bomlu platform mu? Karşılaştırma", "Yüksekte çalışma İSG mevzuatı özetleri", "Operatör belgesi ve eğitim süreçleri", "İş öncesi kontrol listeleri (indirilebilir)"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Türkiye geneli · bilgi kaynağı",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "ekipman seçimi, yüksekte çalışma güvenliği ve saha kontrolü",
        kategori: "rehber",
        bolumler: [
            { baslik: "Telehandler mi, bomlu platform mu? Makine seçim rehberi", href: "/rehber/telehandler-mi-bomlu-platform-mu" },
            { baslik: "Makaslı mı, eklemli mi, teleskopik mi? Platform tipi seçim rehberi", href: "/rehber/platform-tipi-secim-rehberi" },
            { baslik: "Yüksekte çalışma mevzuatı: 6331 kapsamında yükümlülükler", href: "/rehber/yuksekte-calisma-mevzuati" },
            { baslik: "Yüksekte çalışma öncesi 10 maddelik kontrol listesi", href: "/rehber/is-oncesi-kontrol-listesi" },
        ],
    },
    {
        host: "platformakademisi.com",
        gaId: "G-3GYGQ0FR9L",
        baslik: "Platform Akademisi | Operatör Eğitimi ve Yetkinlik Kaynağı",
        aciklama: "Yükseltici platform operatörlüğü eğitim kaynağı: IPAF ve MYK belgelendirme yolları, güvenli kullanım teknikleri, sınav hazırlık notları.",
        h1: "Platform Akademisi",
        paragraflar: [
            "Platform Akademisi, yükseltici platform (manlift) operatörlüğüne adım atanlar ve belgesini yenileyecekler için hazırlanan eğitim kaynağıdır. MYK Ulusal Yeterlilik ve IPAF belgelendirme yollarını, sınav içeriklerini ve başvuru adımlarını sade Türkçeyle anlatıyoruz.",
            "Güvenli kullanım teknikleri, günlük makine kontrolleri, devrilme ve sıkışma risklerine karşı saha kuralları gibi pratik konular; gerçek şantiye senaryoları üzerinden işlenir.",
            "Eğitim takvimi ve içerik duyuruları bu sayfadan yayınlanacaktır; kurumsal ekip eğitimleri için ana sitemizden bize ulaşabilirsiniz.",
        ],
        hizmetler: ["MYK operatör belgesi başvuru rehberi", "IPAF eğitimi nedir, nasıl alınır?", "Günlük makine kontrol listeleri", "Saha güvenlik kuralları ve senaryolar", "Kurumsal ekip eğitimi organizasyonu"],
        anaSite: { ad: "Artı Platform", url: "https://www.artiplatform.com.tr" },
        bolge: "Türkiye geneli · eğitim kaynağı",
        telefon: "+905305518961",
        telefonGosterim: "0530 551 89 61",
        eposta: "kiralama@artiplatform.com.tr",
        uzmanlik: "operatör yetkinliği, günlük kontrol ve güvenli kullanım",
        kategori: "egitim",
    },
];

export function hostIcinSite(host: string): SiteIcerik | undefined {
    const temiz = host.toLowerCase().replace(/^www\./, "").split(":")[0];
    return siteler.find((s) => s.host === temiz);
}
