import type { Yazi } from "@/lib/yazilar";

export const guvenliKategoriler = ["Mevzuat", "Saha Güvenliği", "Ekipman", "Eğitim", "Sektör"] as const;

export const guvenliYazilar: Yazi[] = [
    {
        slug: "yuksekte-calisma-yonetmeligi-isverenin-yukumlulukleri",
        kategori: "Mevzuat",
        baslik: "Yüksekte Çalışmada İşverenin Yükümlülükleri: Mevzuatın Sahaya Çevirisi",
        ozet: "6331 sayılı Kanun ve İnşaat İşlerinde İş Sağlığı ve Güvenliği Yönetmeliği yüksekte çalışmayı nasıl tanımlıyor, işverenden somut olarak ne istiyor? Maddeleri saha diline çevirdik.",
        tarih: "2026-07-20",
        paragraflar: [
            "Türk mevzuatında yüksekte çalışma, seviye farkı bulunan ve düşme sonucu yaralanma ihtimali olan her çalışmayı kapsar. Yaygın kanının aksine belirli bir metre eşiği yoktur: bir metrelik seviye farkı bile, düşme riski doğuruyorsa yüksekte çalışma sayılır ve aynı yükümlülükleri tetikler.",
            "İşverenin ilk yükümlülüğü işi planlamaktır: çalışma başlamadan önce risk değerlendirmesi yapılmalı, toplu koruma önlemleri (korkuluk, platform, güvenlik ağı) kişisel önlemlere (emniyet kemeri) göre öncelikli olarak değerlendirilmelidir. Mevzuat bu hiyerarşiyi açıkça kurar; kemer, korkuluğun yerine geçmez.",
            "İkinci yükümlülük ekipman seçimidir: yapılan işe uygun, periyodik kontrolü yapılmış ekipman kullanılmalıdır. Yükseltici platformlar için bu, yılda en az bir kez yetkili teknik elemanca yapılan periyodik kontrol ve her vardiya öncesi operatör kontrolü demektir.",
            "Üçüncü yükümlülük eğitimdir: yüksekte çalışacak personele işe özgü eğitim verilmeli, yükseltici platform kullanan operatörlerin belgeleri bulunmalıdır. Eğitim kayıtları denetimde ilk istenen evraklar arasındadır.",
            "Güvenli Yükseliş olarak bu başlıkta yönetmelik değişikliklerini ve Yargıtay'ın iş kazası kararlarından çıkan içtihatları düzenli olarak izleyip sadeleştireceğiz.",
        ],
    },
    {
        slug: "bomlu-platformda-emniyet-kemeri-neden-tartisilmaz",
        kategori: "Saha Güvenliği",
        baslik: "Bomlu Platformda Emniyet Kemeri Neden Tartışılmaz?",
        ozet: "Makaslı platformda korkuluk çoğu durumda yeterliyken bomlu platformda tam vücut kemeri zorunlu. Fırlama etkisi (catapult effect) bu farkın nedeni — mekanizmayı ve doğru bağlantı noktasını anlatıyoruz.",
        tarih: "2026-07-20",
        paragraflar: [
            "Bomlu (eklemli veya teleskopik) platformlarda sepet, uzun bir kaldıraç kolunun ucundadır. Makine bir çukura girdiğinde, bir engelle karşılaştığında ya da ani bir hareket yaptığında bu kol bir mancınık gibi davranır ve sepetteki çalışanı yukarı doğru fırlatabilir. Sektörde 'catapult effect' denen bu mekanizma, korkuluğun koruyamayacağı bir risktir.",
            "Bu nedenle bomlu platformlarda tam vücut emniyet kemeri ve kısa lanyard kullanımı tartışmasız kuraldır: amaç düşmeyi durdurmak değil, çalışanı sepetin içinde tutmaktır. Lanyard uzun seçilirse çalışan sepetten fırladıktan sonra havada sallanır — koruma amacı ortadan kalkar.",
            "Bağlantı noktası da kritiktir: kemer, sepetin korkuluğuna değil, üretici tarafından işaretlenmiş ankraj noktasına bağlanmalıdır. Her sepette bu nokta bulunur ve kullanım kılavuzunda gösterilir.",
            "Makaslı platformlarda ise sepet doğrudan şasinin üzerinde dikey hareket eder; fırlama etkisi yoktur. Bu yüzden korkulukları sağlam ve kapısı kapalı bir makaslı platformda kemer, üretici aksini söylemedikçe zorunlu değildir. İki makine tipi arasındaki bu fark, saha eğitimlerinde en sık yanlış anlatılan konulardan biridir.",
        ],
    },
    {
        slug: "yukseltici-platform-periyodik-kontrol-rehberi",
        kategori: "Ekipman",
        baslik: "Yükseltici Platformda Periyodik Kontrol: Neye, Ne Sıklıkla Bakılır?",
        ozet: "İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği'ne göre kaldırma ekipmanlarının kontrol periyotları, kontrolü kimin yapabileceği ve raporda aranacak başlıklar.",
        tarih: "2026-07-20",
        paragraflar: [
            "Yükseltici platformlar, İş Ekipmanlarının Kullanımında Sağlık ve Güvenlik Şartları Yönetmeliği kapsamında kaldırma ve iletme ekipmanı sayılır. Standartlarda aksi belirtilmedikçe yılda en az bir kez, yetkili makine mühendisi, makine teknikeri veya yüksek teknikeri tarafından periyodik kontrole tabi tutulmaları gerekir.",
            "Periyodik kontrol raporunda şu başlıklar aranmalıdır: yük testi sonucu, hidrolik sistem ve hortum kontrolleri, acil indirme düzeneğinin çalışması, korkuluk ve giriş kapısı kilitleri, denge (tilt) sensörü ve limit anahtarlarının testi.",
            "Yıllık kontrol tek başına yeterli değildir: operatörün her vardiya başında yaptığı günlük kontrol — lastikler, akü/yakıt, kumanda fonksiyonları, acil stop, korkuluklar — kayıt altına alınmalıdır. Ciddi kazaların önemli bölümü, günlük kontrolde yakalanabilecek arızalardan çıkar.",
            "Kiralık makinelerde sorumluluk paylaşımı sözleşmeyle netleştirilmelidir: periyodik kontrol raporunu kiralayan firma sağlar, günlük kontrol ve doğru kullanım kiracının yükümlülüğündedir. Raporun bir kopyasının makineyle birlikte sahada bulunması denetimlerde zaman kazandırır.",
        ],
    },
    {
        slug: "myk-ve-ipaf-operator-belgesi-farklari",
        kategori: "Eğitim",
        baslik: "MYK Belgesi mi, IPAF Kartı mı? Operatör Belgelendirmesinde Yol Haritası",
        ozet: "Türkiye'de yükseltici platform operatörünün hangi belgeye ihtiyacı var? MYK Ulusal Yeterlilik ile uluslararası IPAF eğitiminin kapsamları, geçerlilikleri ve hangi durumda hangisinin arandığı.",
        tarih: "2026-07-20",
        paragraflar: [
            "Türkiye'de tehlikeli ve çok tehlikeli işlerde çalışanların Mesleki Yeterlilik Kurumu (MYK) belgesine sahip olması esastır. Yükseltici platform operatörlüğü için ilgili ulusal yeterlilik üzerinden teorik ve pratik sınavla belge alınır; belge, yetkilendirilmiş belgelendirme kuruluşlarınca düzenlenir.",
            "IPAF (International Powered Access Federation) eğitimi ise uluslararası geçerliliğe sahip bir sektör standardıdır: PAL Card, makine kategorilerine (3a makaslı, 3b bomlu vb.) göre verilir ve beş yıl geçerlidir. Uluslararası projelerde, denetimli büyük şantiyelerde ve yabancı ana yüklenicilerin sahalarında sıkça şart koşulur.",
            "İki belge birbirinin alternatifi değil tamamlayıcısıdır: yasal zorunluluğu MYK karşılar, IPAF ise işverene uluslararası standartta eğitim güvencesi verir. Bütçesi kısıtlı işletmeler için önerilen sıra, önce MYK belgesinin tamamlanması, uluslararası saha gereksinimi doğduğunda IPAF eğitiminin eklenmesidir.",
            "Belgesiz operatör çalıştırmanın sonucu yalnız idari para cezası değildir: kaza hâlinde işverenin kusur oranı artar, sigorta rücu riski doğar. Kiralama sözleşmelerinde 'operatör belgesini kiracı sağlar' maddesi varsa belge kontrolü fiilen kiracının İSG ekibine düşer.",
        ],
    },
    {
        slug: "insaatta-dusme-kazalari-veriler-ve-onlemler",
        kategori: "Sektör",
        baslik: "İnşaatta Ölümlü Kazaların Değişmeyen Birincisi: Yüksekten Düşme",
        ozet: "Resmî istatistiklerde inşaat sektöründeki ölümlü iş kazalarının en büyük payı yüksekten düşmede. Verinin anlattıkları ve düşme kazalarını azalttığı kanıtlanmış dört uygulama.",
        tarih: "2026-07-20",
        paragraflar: [
            "SGK iş kazası istatistiklerinde inşaat, ölümlü kazaların en yoğun görüldüğü sektör; yüksekten düşme ise bu kazaların açık ara en büyük nedeni olarak yıllardır ilk sırada. Tablo yıldan yıla küçük oynamalar gösterse de yapısı değişmiyor: düşmeler çoğunlukla korunmasız döşeme kenarlarından, iskelelerden ve çatılardan yaşanıyor.",
            "Kanıtlanmış birinci önlem, geçici kenar korumasının (korkuluk) projelendirme aşamasında planlanmasıdır: koruma, iş başladıktan sonra 'eklenen' değil, işin metoduna baştan gömülen bir kalem olduğunda uygulanma oranı belirgin artar.",
            "İkincisi, merdiven ve iskele yerine mekanize erişimdir: kısa süreli yüksekte çalışmalarda yükseltici platform kullanımı, hem düşme riskini hem de kas-iskelet yüklenmesini azaltır. Avrupa verileri, platform kullanımının yaygınlaştığı işlerde düşme kaynaklı kayıp gün sayısının düştüğünü gösteriyor.",
            "Üçüncüsü çalışma izin sistemidir: yüksekte çalışma iznini, işi yapan ekipten bağımsız bir yetkilinin onaylaması, atlanmış önlemleri işe başlamadan yakalar. Dördüncüsü ise kısa ve işe özgü eğitim tekrarlarıdır: uzun yıllık eğitimler yerine, o günkü işin risklerine odaklanan beş dakikalık başlangıç konuşmaları (toolbox talk) sahada davranışı daha çok değiştiriyor.",
            "Güvenli Yükseliş bu sayfada sektör istatistiklerini her yayım döneminde güncelleyecek; okuyucularımızın sahadan aktardığı ramak kala vakaları, kimlik bilgisi olmadan derlenip herkesin dersine sunulacak.",
        ],
    },
    {
        slug: "yukseltici-platformda-ruzgar-limiti-hava-kosullari",
        kategori: "Saha Güvenliği",
        baslik: "Yükseltici Platformda Rüzgâr Limiti: Üretici Verisi Neden Bağlayıcı?",
        ozet: "Her yükseltici platformun kullanım kılavuzunda azami rüzgâr hızı yazar — bu sayı keyfi değil, sepetin devrilme momentine göre hesaplanmıştır. Sahada bu limiti göz ardı etmenin gerçek riski.",
        tarih: "2026-07-21",
        paragraflar: [
            "Yükseltici platformların çoğu, imalatçı tarafından belirlenmiş azami rüzgâr hızında (genellikle 12,5 m/s, saatte yaklaşık 45 km) çalışacak şekilde tasarlanır ve test edilir. Bu sayı, makinenin yükseklikte açık sepet yüzeyinin rüzgâra karşı oluşturduğu devirme momentine göre hesaplanır.",
            "Sahada en sık yapılan hata, 'rüzgâr hafif esiyor' gibi öznel bir değerlendirmeyle işe devam etmektir. Doğru uygulama, sahada anemometre bulundurmak ve ölçülen değeri kılavuzdaki limitle karşılaştırmaktır; özellikle bina cepheleri ve açık sahil şeridi gibi rüzgârı hızlandıran noktalarda yerel etkiler ölçüm olmadan tahmin edilemez.",
            "Yükseklik arttıkça rüzgâr hızı da artar — zeminde ölçülen değer, 20 metre yukarıdaki gerçek rüzgârı yansıtmaz. Bu nedenle büyük yükseklikli operasyonlarda saha ölçümü, meteorolojik tahminden daha güvenilir bir referanstır.",
            "Rüzgâr limitini aşan koşullarda çalışmaya devam etmenin sonucu yalnız devrilme değildir: sepetteki yükün fırlaması, kumanda hassasiyetinin bozulması ve acil iniş sırasında kontrolsüz hareket de rapor edilen kaza türleri arasındadır. Güvenli Yükseliş, hava koşulu kaynaklı olayları ayrı bir başlık altında izlemeye devam edecek.",
        ],
    },
    {
        slug: "kapali-alanda-yukseklik-riski-tank-silo-ici-calisma",
        kategori: "Saha Güvenliği",
        baslik: "Kapalı Alanda Yükseklik Riski: Tank ve Silo İçi Çalışmalar",
        ozet: "Kapalı alan çalışması denince akla gaz riski gelir, ama tank ve silo içindeki yüksekte çalışma boyutu çoğu zaman ihmal edilir. İki riskin üst üste bindiği bu işler için özel önlemler.",
        tarih: "2026-07-21",
        paragraflar: [
            "Tank temizliği, silo bakımı ve rezervuar içi kaynak işleri, aynı anda hem kapalı alan hem de yükseklik riski taşır. Standart kapalı alan prosedürleri (gaz ölçümü, havalandırma, gözcü personel) bu işlerde tek başına yeterli değildir — iç hacimde kurulan iskele veya asma platformun stabilitesi ayrı bir değerlendirme gerektirir.",
            "Bu ortamlarda standart yükseltici platformlar genellikle kullanılamaz; bunun yerine özel tasarlanmış iç iskele sistemleri veya kompakt dikey platformlar tercih edilir. Ekipman seçimi, tankın iç çapı, giriş ağzının boyutu ve zemin taşıma kapasitesine göre yapılmalıdır.",
            "Acil tahliye planı bu işlerde kritik önem taşır: kapalı alan içinde yaralanan bir çalışanın tahliyesi, hem gaz riski hem yükseklik nedeniyle standart kurtarma yönteminden farklı ekipman (üç ayaklı vinç, tripod) gerektirebilir. Bu ekipmanın işe başlamadan önce sahada hazır bulunması şarttır.",
            "Güvenli Yükseliş, kapalı alan ve yükseklik risklerinin üst üste bindiği işler için saha uygulamalarını ve ekipman seçim kriterlerini bu başlık altında derlemeye devam edecek.",
        ],
    },
    {
        slug: "yukseltici-platform-devrilme-kazalari-nedenleri",
        kategori: "Sektör",
        baslik: "Yükseltici Platform Devrilme Kazaları: Ortak Nedenler",
        ozet: "Devrilme, yükseltici platform kazalarının en ağır sonuçlananları arasında. İnceleme raporlarında tekrar eden dört neden ve bunların önlenebilirlik düzeyi.",
        tarih: "2026-07-21",
        paragraflar: [
            "Yükseltici platform devrilme kazalarını inceleyen raporlarda dört neden düzenli olarak öne çıkıyor: eğimli veya sağlam olmayan zeminde çalışma, izin verilen yük kapasitesinin aşılması, aşırı uzatılmış bom açısında yanal yük binmesi ve stabilizatör ayaklarının doğru açılmaması.",
            "Zemin kaynaklı devrilmelerin büyük kısmı, makinenin kendi seviye sensörünün (tilt alarm) uyarısına rağmen çalışmaya devam edilmesinden kaynaklanıyor. Bu alarm bir öneri değil, dur sinyalidir — sistemin devre dışı bırakılması veya görmezden gelinmesi kaza raporlarında tekrarlayan bir bulgu.",
            "Yük kapasitesi aşımı genellikle malzeme + personel toplamının hesaba katılmamasından doğuyor: sepete alınan boru, panel gibi malzemenin ağırlığı, üreticinin belirttiği azami kapasiteye eklenmelidir; bu hesap saha ekibi tarafından değil, iş planlama aşamasında yapılmalıdır.",
            "Güvenli Yükseliş, devrilme kazalarına ilişkin kamuya açık inceleme raporlarını takip edip çıkarılan dersleri bu sayfada okuyucularımızla paylaşmayı sürdürecek.",
        ],
    },
    {
        slug: "genc-deneyimsiz-operator-egitim-mentorluk-suresi",
        kategori: "Eğitim",
        baslik: "Genç ve Deneyimsiz Operatörde Kaza Riski Neden Daha Yüksek?",
        ozet: "İş kazası istatistiklerinde ilk altı ayın çalışanı, kıdemli meslektaşına göre orantısız yüksek risk taşıyor. Bu farkı kapatan mentorluk ve kademeli yetkilendirme uygulamaları.",
        tarih: "2026-07-21",
        paragraflar: [
            "Uluslararası iş güvenliği verileri, bir işe yeni başlayan çalışanın ilk altı ayda kaza geçirme olasılığının, aynı işi yıllardır yapan meslektaşına göre belirgin şekilde yüksek olduğunu gösteriyor. Yükseltici platform operatörlüğünde de bu örüntü geçerlidir: belge almış ama saha tecrübesi az olan operatörler, ramak kala olaylarında ağırlıklı olarak görülüyor.",
            "Bunun nedeni yalnız bilgi eksikliği değil — risk sezgisinin oluşması zaman alır. Belgeli bir operatör makinenin kumandalarını doğru kullanabilir, ama saha koşullarının (zemin, rüzgâr, çevredeki diğer ekipler) ne zaman 'normalin dışında' olduğunu ayırt etme becerisi tecrübeyle gelişir.",
            "Kademeli yetkilendirme bu açığı kapatan kanıtlanmış bir uygulamadır: yeni operatör ilk haftalarda düşük riskli işlerde ve deneyimli bir operatörün gözetiminde çalışır, kademeli olarak daha karmaşık işlere geçer. Bu, belge sahibi olmakla 'sahaya hazır olmak' arasındaki farkı azaltır.",
            "Güvenli Yükseliş, işe yeni başlayan operatörler için mentorluk uygulamalarını ve işverenlerin bu süreci nasıl yapılandırdığını bu başlık altında incelemeye devam edecek.",
        ],
    },
    {
        slug: "kisisel-koruyucu-donanim-secimi-yukseklik-icin-dogru-kemer",
        kategori: "Ekipman",
        baslik: "Yükseklik İçin Doğru Kişisel Koruyucu Donanım Nasıl Seçilir?",
        ozet: "Tam vücut kemeri, lanyard tipi ve bağlantı noktası — piyasadaki KKD çeşitliliği karşısında işin gerçek riskine uygun seçim nasıl yapılır?",
        tarih: "2026-07-21",
        paragraflar: [
            "Yükseklikte çalışma için kullanılan kişisel koruyucu donanım (KKD) tek tip değildir: tam vücut emniyet kemeri, enerji emici lanyard, kendinden geri çekmeli düşme durdurucu (SRL) ve pozisyonlama kemeri, farklı iş türleri için tasarlanmıştır ve birbirinin yerine geçmez.",
            "Yükseltici platform sepetinde çalışan bir operatör için genellikle kısa, enerji emici olmayan bir lanyard yeterlidir — çünkü amaç düşmeyi durdurmak değil, sepette tutmaktır. Buna karşılık iskele üzerinde veya çatı kenarında serbest yükseklikte çalışan biri için enerji emici lanyard veya SRL zorunludur; kısa bir lanyard burada yetersiz kalır.",
            "Ekipman seçiminde sık yapılan hata, maliyet veya stokta bulunabilirliğe göre karar vermektir. Doğru yaklaşım, önce işin düşme mesafesini ve olası sarkaç etkisini hesaplamak, ardından bu hesaba uygun KKD kategorisini belirlemektir — bu hesap iş güvenliği uzmanının sorumluluğundadır.",
            "Güvenli Yükseliş, KKD seçim kriterlerini ve sahada sık karşılaşılan yanlış kullanım örneklerini bu sayfada derlemeyi sürdürecek.",
        ],
    },
    {
        slug: "alt-yuklenici-isg-sorumluluk-paylasimi-santiyede",
        kategori: "Mevzuat",
        baslik: "Şantiyede Alt Yüklenici İSG Sorumluluğu Kimde?",
        ozet: "Ana yüklenici, alt yüklenici ve ekipman kiralayan firma arasında İSG sorumluluğu nasıl paylaşılır? Sözleşmede netleştirilmesi gereken üç madde.",
        tarih: "2026-07-21",
        paragraflar: [
            "Çok katmanlı yüklenici yapısına sahip şantiyelerde İSG sorumluluğunun kimde olduğu sorusu, kaza sonrası hukuki süreçlerde sıkça belirsizlik yaratıyor. Mevzuat, işveren tanımını geniş tutar: sahadaki tüm çalışanların güvenliğinden asıl işveren ile alt işveren müştereken ve müteselsilen sorumludur.",
            "Bu, alt yüklenicinin kendi personeli için aldığı önlemlerin, ana yüklenicinin genel saha düzenlemesiyle (ortak geçiş yolları, ortak iskele, ortak acil durum planı) uyumlu olması gerektiği anlamına gelir. Alt yüklenicinin 'kendi işim, kendi sorumluluğum' yaklaşımı hukuken yeterli değildir.",
            "Ekipman kiralayan firmanın sorumluluğu ise genellikle sözleşmeyle sınırlıdır: periyodik kontrol raporunu sağlamak ve makinenin teknik olarak sağlam teslim edilmesi kiralayan firmanın yükümlülüğüdür; günlük kontrol ve doğru kullanım ise kiracının sorumluluğunda kalır. Bu ayrımın sözleşmede açıkça yazılması, kaza sonrası taraflar arası ihtilafı azaltır.",
            "Güvenli Yükseliş, çok yüklenicili şantiye yapılarında İSG sorumluluk paylaşımını ve sözleşme uygulamalarını bu başlık altında ele almaya devam edecek.",
        ],
    },
    {
        slug: "is-kazasi-sonrasi-hukuki-surec-isverenin-adimlari",
        kategori: "Mevzuat",
        baslik: "İş Kazası Sonrası İlk 48 Saat: İşverenin Atması Gereken Adımlar",
        ozet: "Bir iş kazası yaşandığında işverenin yasal bildirim yükümlülükleri, delil koruma süreci ve sık yapılan hatalar.",
        tarih: "2026-07-21",
        paragraflar: [
            "İş kazası yaşandığında işverenin ilk yükümlülüğü, olayı SGK'ya derhâl, en geç kazadan sonraki üç iş günü içinde bildirmektir. Bu bildirim, kazanın nasıl gerçekleştiğine dair ilk resmî kaydı oluşturur ve sonraki incelemelerin temelini teşkil eder.",
            "Kaza yerinin, incelemeyi yapacak yetkililer (iş müfettişi, kolluk) gelene kadar mümkün olduğunca değiştirilmemesi önemlidir — ekipmanın erken kaldırılması veya sahanın temizlenmesi, sonradan işverenin aleyhine yorumlanabilecek bir delil kaybına yol açabilir.",
            "Sık yapılan hatalardan biri, olay anına ait tanık ifadelerinin zamanında ve tarafsız şekilde alınmamasıdır. Zaman geçtikçe hafıza netliği azalır; kaza sonrası ilk saatlerde alınan yazılı beyanlar, sonraki hukuki süreçte belirleyici olabilir.",
            "Güvenli Yükseliş, iş kazası sonrası süreç yönetimini ve işverenlerin bu süreçte en sık karşılaştığı soruları bu başlık altında yanıtlamaya devam edecek.",
        ],
    },
];
