import Image from "next/image";
import { hostBloglari } from "@/lib/blog";
import type { SiteIcerik } from "@/lib/siteler";
import { TemaForm } from "./tema-form";
import type { TemaModulu } from "./tipler";

const ikonlar = {
    ok: "M5 12h14M13 5l7 7-7 7",
    telefon: "M22 16.92v3a2 2 0 0 1-2.18 2A19.79 19.79 0 0 1 3.09 5.18 2 2 0 0 1 5.08 3h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L9.06 10.91a16 16 0 0 0 4 4l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z",
    posta: "M4 4h16v16H4zM22 6l-10 7L2 6",
    konum: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1 1 18 0zM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z",
    onay: "M20 6L9 17l-5-5",
};
function Ikon({ ad, className = "h-5 w-5" }: { ad: keyof typeof ikonlar; className?: string }) {
    return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={ikonlar[ad]} /></svg>;
}

const makineler = [
    { baslik: "Makaslı Platformlar", alt: "8–18 metre", metin: "Fabrika içi bakım, raf ve tavan işlerinde geniş çalışma alanı.", gorsel: "/media/makasli-platform.png", slug: "makasli-platform-kiralama" },
    { baslik: "Eklemli Platformlar", alt: "16–32 metre", metin: "Üretim hattı ve yapı engellerinin arkasına hassas erişim.", gorsel: "/media/eklemli-platform.png", slug: "eklemli-ve-teleskopik-platform-kiralama" },
    { baslik: "Teleskopik Platformlar", alt: "Yüksek erişim", metin: "Açık saha çelik montajı, baca ve cephe işleri için uzun erişim.", gorsel: "/media/blog/dikey-personel-yukseltici-arti-platform-makine-parki.jpg", slug: "eklemli-ve-teleskopik-platform-kiralama" },
];

function Cerceve({ site, aktif = "", children }: Parameters<TemaModulu["Cerceve"]>[0]) {
    const nav = [["/", "Ana Sayfa"], ["/hakkimizda", "Hakkımızda"], ["/urunler", "Ürünler"], ["/blog", "Blog"], ["/iletisim", "İletişim"]];
    return <div className="min-h-screen bg-[#faf5ee] text-[#3a302a] font-['Manrope']">
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500;600;700;800&family=Manrope:wght@400;500;600;700&display=swap" />
        <header className="sticky top-0 z-50 border-b border-white/40 bg-[#faf5ee]/70 backdrop-blur-md"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-4 md:px-8"><a href="/" className="font-['EB_Garamond'] text-[24px] font-extrabold tracking-tight text-[#3a302a]">Bilecik Platform Kiralama</a><nav className="hidden gap-6 md:flex">{nav.map(([h, e]) => <a key={h} href={h} className={`border-b-2 pb-1 text-[14px] font-bold transition-colors ${aktif === h ? "border-[#78706a] text-[#78706a]" : "border-transparent text-[#605850] hover:text-[#78706a]"}`}>{e}</a>)}</nav><div className="flex gap-4"><a href="/iletisim" className="hidden rounded-[8px] border border-[#d8d0c8] px-5 py-2.5 text-[14px] font-semibold md:block">Teklif Al</a><a href={`tel:${site.telefon}`} className="rounded-[8px] bg-[#c2652a] px-5 py-2.5 text-[14px] font-semibold text-white">Hemen Ara</a></div></div></header>
        <main>{children}</main>
        <footer className="border-t border-[#504840]/20 bg-[#3a302a] px-8 py-24 text-[#faf5ee]"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-12 md:flex-row"><div className="max-w-sm"><h2 className="font-['EB_Garamond'] text-[32px] font-bold text-[#f0a878]">Bilecik Platform</h2><p className="mt-4 text-[14px] leading-6 text-[#cec6be]">{site.uzmanlik} için doğrulanabilir saha planı ve teklif.</p></div><div className="grid grid-cols-2 gap-x-16 gap-y-3 text-[14px] text-[#cec6be]">{nav.slice(1).map(([h, e]) => <a href={h} key={h} className="hover:text-white">{e}</a>)}<a href={site.anaSite.url}>{site.anaSite.ad}</a></div><div><a href={`tel:${site.telefon}`} className="flex gap-3"><Ikon ad="telefon" />{site.telefonGosterim}</a><a href={`mailto:${site.eposta}`} className="mt-3 flex gap-3 break-all"><Ikon ad="posta" />{site.eposta}</a></div></div></footer>
        <a href={`tel:${site.telefon}`} aria-label="Bilecik Platform'u ara" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#c2652a] text-white shadow-xl"><Ikon ad="telefon" /></a>
    </div>;
}

function AnaSayfa({ site }: { site: SiteIcerik }) {
    return <><section className="mx-auto grid max-w-[1440px] items-center gap-12 px-8 py-12 md:py-24 lg:grid-cols-2"><div className="max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d8d0c8]/50 bg-[#ece6dc] px-3 py-1 text-[12px] text-[#605850]"><span className="h-2 w-2 rounded-full bg-[#c2652a]" />{site.bolge}</div><h1 className="font-['EB_Garamond'] text-[48px] font-semibold leading-tight text-[#3a302a] md:text-[72px]">{site.h1}<br /><span className="italic text-[#c2652a]">Profesyonel Çözümler.</span></h1><p className="mt-6 text-[18px] leading-8 text-[#605850]">{site.paragraflar[0]}</p><div className="mt-8 flex flex-wrap gap-4"><a href="/iletisim" className="rounded-[8px] bg-[#c2652a] px-6 py-3 font-semibold text-white">Teklif İsteyin</a><a href="/urunler" className="rounded-[8px] border border-[#d8d0c8] px-6 py-3 font-semibold">Filoyu İnceleyin</a></div></div><div className="relative min-h-[560px] overflow-hidden rounded-[12px]"><Image src="/media/saha-hero.png" alt="Bilecik platform kiralama sahası" fill priority sizes="50vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#3a302a]/50 to-transparent" /><div className="absolute bottom-6 left-6 right-6 rounded-[8px] bg-[#faf5ee]/90 p-6 backdrop-blur-md"><p className="text-[14px] font-semibold text-[#3a302a]">Güncel uygunluk • Yazılı kapsam • Planlı sevkiyat</p></div></div></section>
        <section className="mx-auto max-w-[1440px] px-8 py-24"><h2 className="font-['EB_Garamond'] text-[40px] text-[#3a302a]">Hizmet başlıkları</h2><p className="mt-3 max-w-2xl text-[#605850]">{site.paragraflar[1]}</p><div className="mt-12 grid gap-8 md:grid-cols-3">{makineler.map((m) => <article key={m.baslik} className="group"><div className="relative h-72 overflow-hidden rounded-[12px]"><Image src={m.gorsel} alt={m.baslik} fill sizes="33vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /></div><span className="mt-6 block text-[12px] font-semibold uppercase tracking-[0.08em] text-[#c2652a]">{m.alt}</span><h3 className="mt-2 font-['EB_Garamond'] text-[28px] text-[#3a302a]">{m.baslik}</h3><p className="mt-3 leading-6 text-[#605850]">{m.metin}</p><a href={`/${m.slug}`} className="mt-5 inline-flex items-center gap-2 font-semibold text-[#c2652a]">Detayları İncele <Ikon ad="ok" /></a></article>)}</div><div className="mt-14 rounded-[12px] bg-[#3a302a] p-8 text-[#faf5ee]"><h3 className="font-['EB_Garamond'] text-[32px]">Güvenilir Operasyon</h3><p className="mt-2 text-[#cec6be]">{site.paragraflar[2]}</p></div></section>
        <section className="border-y border-[#d8d0c8]/30 bg-[#f6f0e8] px-8 py-24"><div className="mx-auto grid max-w-[1440px] gap-16 lg:grid-cols-[1fr_2fr]"><h2 className="font-['EB_Garamond'] text-[40px] text-[#3a302a] lg:sticky lg:top-32 lg:self-start">İhtiyacınızı birlikte netleştirelim.</h2><div className="space-y-12">{["İşi tarif edin", "Uygunluğu kontrol edelim", "Yazılı teklif alın"].map((a, i) => <article key={a} className="grid gap-5 border-b border-[#d8d0c8] pb-10 sm:grid-cols-[64px_1fr]"><span className="font-['Manrope'] text-[13px] font-semibold tracking-[0.1em] text-[#c2652a]">0{i + 1}</span><div><h3 className="font-['EB_Garamond'] text-[28px] text-[#3a302a]">{a}</h3><p className="mt-3 leading-7 text-[#605850]">{site.paragraflar[Math.min(i, site.paragraflar.length - 1)]}</p></div></article>)}</div></div></section><section className="mx-auto max-w-[1440px] px-8 py-24 text-center"><h2 className="mx-auto max-w-3xl font-['EB_Garamond'] text-[40px] text-[#3a302a] md:text-[52px]">Saha bilgilerinizi paylaşın, doğrulanabilir teklif hazırlayalım.</h2><a href="/iletisim" className="mt-8 inline-flex rounded-[8px] bg-[#c2652a] px-7 py-4 font-semibold text-white">Teklif Hazırlığına Başlayın</a></section></>;
}

function IcBaslik({ etiket, baslik, metin }: { etiket: string; baslik: string; metin?: string }) {
    return <section className="px-8 pb-12 pt-24"><div className="mx-auto max-w-[1440px]"><p className="text-[13px] font-semibold tracking-[0.12em] text-[#c2652a]">{etiket}</p><h1 className="mt-4 max-w-4xl font-['EB_Garamond'] text-[48px] font-medium leading-tight text-[#3a302a] md:text-[72px]">{baslik}</h1>{metin && <p className="mt-6 max-w-3xl text-[18px] leading-8 text-[#605850]">{metin}</p>}</div></section>;
}
function Hakkimizda({ site }: { site: SiteIcerik }) {
    return <><section className="mx-auto flex max-w-6xl flex-col items-center gap-16 px-6 py-24 lg:flex-row lg:px-12 lg:py-32"><div className="flex-1"><p className="mb-4 text-[13px] font-semibold tracking-[0.12em] text-[#c2652a]">KURUMSAL PROFİLİMİZ</p><h1 className="font-['EB_Garamond'] text-[48px] font-semibold leading-tight text-[#3a302a] lg:text-[72px]">Yerel Saha Bilgisi,<br /><span className="italic text-[#c2652a]">Kurumsal İş Disiplini.</span></h1><p className="mt-6 text-[18px] leading-8 text-[#605850]">{site.paragraflar[0]}</p></div><div className="relative min-h-[520px] w-full flex-1 overflow-hidden rounded-[12px]"><Image src="/media/guvenli-calisma.png" alt="Bilecik güvenli platform operasyonu" fill sizes="50vw" className="object-cover" /></div></section><section className="mx-auto grid max-w-6xl gap-8 px-6 py-20 lg:grid-cols-2 lg:px-12">{["Misyonumuz", "Vizyonumuz"].map((b, i) => <article key={b} className="rounded-[12px] bg-[#f6f0e8] p-10"><h2 className="font-['EB_Garamond'] text-[36px] font-semibold text-[#3a302a]">{b}</h2><p className="mt-4 leading-7 text-[#605850]">{site.paragraflar[i + 1] ?? site.hizmetler[i]}</p></article>)}</section><section className="my-10 border-y border-[#d8d0c8]/30 px-6 py-24"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-4"><h2 className="font-['EB_Garamond'] text-[40px] font-semibold text-[#3a302a] md:col-span-2">Sayılarla Bilecik Platform</h2>{[["8–32 m", "Erişim sınıfları"], ["4", "Hizmet bölgesi"], ["7/24", "Talep hattı"], ["%100", "Yazılı kapsam"]].map(([s, e]) => <div key={e}><strong className="font-['EB_Garamond'] text-[44px] text-[#c2652a]">{s}</strong><p className="text-[#605850]">{e}</p></div>)}</div></section><section className="mx-auto max-w-4xl px-6 py-20 text-center"><h3 className="font-['EB_Garamond'] text-[36px] font-medium leading-snug text-[#3a302a]">Sahadaki belirsizliği azaltan, açık ve doğrulanabilir bir kiralama süreci.</h3><a href="/iletisim" className="mt-8 inline-flex rounded-[8px] bg-[#c2652a] px-7 py-4 font-semibold text-white">Bizimle İletişime Geçin</a></section></>;
}
function Urunler() {
    return <><IcBaslik etiket="PLATFORM VE FORKLİFT ÇÖZÜMLERİ" baslik="Makine Filomuz" /><section className="mx-auto max-w-[1440px] space-y-24 px-8 pb-24">{makineler.map((m, i) => <article key={m.baslik} className="grid items-center gap-12 lg:grid-cols-2"><div className={`relative min-h-[430px] overflow-hidden rounded-[12px] ${i % 2 ? "lg:order-2" : ""}`}><Image src={m.gorsel} alt={m.baslik} fill sizes="50vw" className="object-cover" /></div><div><span className="text-[12px] font-semibold uppercase tracking-[0.1em] text-[#c2652a]">{m.alt}</span><h2 className="mt-3 font-['EB_Garamond'] text-[40px] text-[#3a302a]">{m.baslik}</h2><p className="mt-4 text-[18px] leading-8 text-[#605850]">{m.metin}</p><div className="mt-6 grid grid-cols-2 gap-4 rounded-[8px] bg-[#f6f0e8] p-6"><div><small className="text-[#605850]">KULLANIM</small><strong className="mt-1 block">İç / dış saha</strong></div><div><small className="text-[#605850]">PLANLAMA</small><strong className="mt-1 block">Saha bilgisine göre</strong></div></div><a href={`/${m.slug}`} className="mt-7 inline-flex rounded-[8px] bg-[#c2652a] px-6 py-3 font-semibold text-white">Ürün Detayı</a></div></article>)}<div className="rounded-[12px] bg-[#3a302a] p-10 text-[#faf5ee]"><h3 className="font-['EB_Garamond'] text-[36px]">Doğru Makineyi Birlikte Seçelim</h3><p className="mt-3 max-w-2xl text-[#cec6be]">Yükseklik, yatay erişim, zemin ve geçiş ölçülerini paylaşın; uygun sınıfı yazılı kapsamla netleştirelim.</p><a href="/iletisim" className="mt-6 inline-flex rounded-[8px] bg-[#c2652a] px-6 py-3 font-semibold text-white">Saha Bilgisi Paylaşın</a></div></section></>;
}
function Iletisim({ site }: { site: SiteIcerik }) {
    const opsiyonlar = site.bolge.split(",").map((x) => x.trim());
    return <main className="mx-auto max-w-7xl px-6 pb-24 pt-24 md:px-12"><header className="mb-16 max-w-3xl md:mb-24"><h1 className="font-['EB_Garamond'] text-[48px] font-medium leading-tight tracking-tight text-[#3a302a] md:text-[72px]">Teklif ve Destek Hattı</h1><p className="mt-6 text-[18px] leading-8 text-[#605850]">Çalışma yüksekliği, zemin, tarih ve adresi iletin; uygun makine sınıfını birlikte netleştirelim.</p></header><div className="grid gap-12 lg:grid-cols-[1fr_1.25fr]"><aside className="space-y-5">{[["telefon", "Hemen ara", site.telefonGosterim, `tel:${site.telefon}`], ["posta", "E-posta gönder", site.eposta, `mailto:${site.eposta}`], ["konum", "Hizmet bölgesi", site.bolge, "/iletisim"]].map(([ikon, b, m, h]) => <a key={b} href={h} className="flex gap-5 rounded-[12px] bg-[#f6f0e8] p-6"><span className="text-[#c2652a]"><Ikon ad={ikon as keyof typeof ikonlar} /></span><span><strong className="block font-['EB_Garamond'] text-[28px] font-medium">{b}</strong><small className="mt-1 block break-all text-[#605850]">{m}</small></span></a>)}</aside><div className="rounded-[12px] bg-white p-8 shadow-[0_2px_16px_rgba(58,48,42,0.04)]"><TemaForm eposta={site.eposta} konu={`Bilecik Platform Teklif Talebi — ${site.h1}`} opsiyonlar={opsiyonlar} cls={{etiket:"mb-2 block text-[14px] font-semibold text-[#3a302a]",alan:"w-full rounded-[8px] border border-[#d8d0c8] bg-[#faf5ee] p-3 outline-none focus:border-[#c2652a]",buton:"w-full rounded-[8px] bg-[#c2652a] px-7 py-4 font-semibold text-white",izgara:"grid gap-5 md:grid-cols-2"}} /></div></div></main>;
}
function BlogListe({ site }: { site: SiteIcerik }) {
    const yazilar = hostBloglari(site.host);
    const ilk = yazilar[0];
    return <main className="mx-auto w-full max-w-[1440px] px-6 pb-24 pt-24 md:px-12"><section className="mb-16 max-w-3xl md:mb-24"><span className="text-[12px] font-semibold uppercase tracking-[0.1em] text-[#c2652a]">BİLGİ MERKEZİ</span><h1 className="mt-4 font-['EB_Garamond'] text-[48px] leading-tight text-[#3a302a] md:text-[72px]">Saha Odaklı Planlama ve Güvenlik Rehberi</h1></section><section className="grid auto-rows-[minmax(300px,_auto)] gap-6 md:grid-cols-3 md:gap-8">{ilk && <article className="group relative col-span-1 row-span-2 flex min-h-[620px] flex-col justify-end overflow-hidden rounded-[12px] md:col-span-2"><Image src={ilk.gorsel} alt={ilk.gorselAlt} fill sizes="66vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#3a302a] via-[#3a302a]/30 to-transparent" /><div className="relative p-8 text-white md:p-12"><span className="text-[12px] font-semibold text-[#f0a878]">{ilk.kategori}</span><h2 className="mt-3 font-['EB_Garamond'] text-[36px] leading-tight md:text-[48px]">{ilk.baslik}</h2><p className="mt-4 line-clamp-3 max-w-2xl text-[#f6f0e8]">{ilk.ozet}</p><a href={`/blog/${ilk.slug}`} className="mt-5 inline-flex items-center gap-2 font-semibold">Rehberi Oku <Ikon ad="ok" /></a></div></article>}{yazilar.slice(1).map((y, i) => <article key={y.slug} className={`group flex flex-col rounded-[12px] border border-[#d8d0c8]/30 bg-[#f6f0e8] p-8 shadow-[0_2px_16px_rgba(58,48,42,0.04)] ${i === 2 ? "md:col-span-2 md:flex-row md:gap-8" : ""}`}><div className="flex-1"><span className="text-[12px] font-semibold text-[#c2652a]">{y.kategori}</span><h3 className="mt-3 font-['EB_Garamond'] text-[28px] leading-snug text-[#3a302a]">{y.baslik}</h3><p className="mt-4 line-clamp-3 flex-1 text-[14px] leading-6 text-[#605850]">{y.ozet}</p><a href={`/blog/${y.slug}`} className="mt-5 inline-flex items-center gap-2 font-semibold text-[#c2652a]">Devamını Oku <Ikon ad="ok" /></a></div></article>)}</section><section className="mx-auto mt-24 max-w-4xl rounded-[16px] border border-[#d8d0c8]/40 bg-[#f2ece4] p-10 text-center md:p-16"><h2 className="font-['EB_Garamond'] text-[36px] text-[#3a302a]">Eksiksiz Bir Saha Dosyası Hazırlayın</h2><p className="mt-4 text-[#605850]">Ölçü, fotoğraf, zemin, tarih ve adres bilgilerini tek dosyada paylaşarak teklif sürecini hızlandırın.</p><a href="/iletisim" className="mt-7 inline-flex rounded-[8px] bg-[#c2652a] px-7 py-4 font-semibold text-white">Saha Bilgisi Paylaşın</a></section></main>;
}

export const bilecikTema: TemaModulu = { Cerceve, AnaSayfa, sayfalar: { hakkimizda: Hakkimizda, iletisim: Iletisim, urunler: Urunler }, BlogListe };
