import Image from "next/image";
import { hostBloglari } from "@/lib/blog";
import type { SiteIcerik } from "@/lib/siteler";
import { TemaForm } from "./tema-form";
import type { TemaModulu } from "./tipler";

const ikonlar = {
    ok: "M5 12h14M13 5l7 7-7 7",
    telefon: "M22 16.92v3a2 2 0 0 1-2.18 2A19.79 19.79 0 0 1 3.09 5.18 2 2 0 0 1 5.08 3h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L9.06 10.91a16 16 0 0 0 4 4l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z",
    posta: "M4 4h16v16H4zM22 6l-10 7L2 6",
    konum: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1 1 18 0zM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z",
    onay: "M20 6L9 17l-5-5",
};
function Ikon({ ad, className = "h-5 w-5" }: { ad: keyof typeof ikonlar; className?: string }) {
    return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={ikonlar[ad]} /></svg>;
}

const makineler = [
    { baslik: "Makaslı Platformlar", alt: "8–18 metre", metin: "Fabrika içi bakım, raf ve tavan işlerinde geniş çalışma alanı.", gorsel: "/media/makasli-platform.png", slug: "makasli-platform-kiralama" },
    { baslik: "Eklemli Platformlar", alt: "16–32 metre", metin: "Üretim hattı ve yapı engellerinin arkasına hassas erişim.", gorsel: "/media/eklemli-platform.png", slug: "eklemli-ve-teleskopik-platform-kiralama" },
    { baslik: "Teleskopik Platformlar", alt: "Yüksek erişim", metin: "Açık saha çelik montajı, baca ve cephe işleri için uzun erişim.", gorsel: "/media/blog/dikey-personel-yukseltici-arti-platform-makine-parki.jpg", slug: "eklemli-ve-teleskopik-platform-kiralama" },
];

function Cerceve({ site, aktif = "", children }: Parameters<TemaModulu["Cerceve"]>[0]) {
    const nav = [["/", "Ana Sayfa"], ["/hakkimizda", "Hakkımızda"], ["/urunler", "Ürünler"], ["/blog", "Blog"], ["/iletisim", "İletişim"]];
    return <div className="min-h-screen bg-[#f8fafc] text-[#0f172a] font-['Manrope']">
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@500;600;700;800&family=Manrope:wght@400;500;600;700&display=swap" />
        <header className="sticky top-0 z-50 border-b border-[#cbd5e1] bg-white/90 backdrop-blur-md"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 md:px-8"><a href="/" className="flex items-center gap-3"><Image src="/media/logo/1.png" alt={`${site.h1} logosu`} width={48} height={48} className="h-11 w-11 object-contain" /><span className="font-['Hanken_Grotesk'] text-[20px] font-extrabold tracking-tight">Bilecik Platform</span></a><nav className="hidden gap-7 lg:flex">{nav.map(([h, e]) => <a key={h} href={h} className={`border-b-2 py-2 text-[14px] font-bold transition-colors ${aktif === h ? "border-[#06b6d4] text-[#0f172a]" : "border-transparent text-[#64748b] hover:text-[#0f172a]"}`}>{e}</a>)}</nav><a href={`tel:${site.telefon}`} className="rounded-[8px] bg-[#0f172a] px-5 py-3 text-[14px] font-bold text-white">Hemen Ara</a></div></header>
        <main>{children}</main>
        <footer className="border-t border-[#334155] bg-[#0f172a] px-6 py-14 text-white"><div className="mx-auto grid max-w-[1440px] gap-10 md:grid-cols-3"><div><h2 className="font-['Hanken_Grotesk'] text-[24px] font-extrabold">Bilecik Platform</h2><p className="mt-4 max-w-sm text-[14px] leading-6 text-[#cbd5e1]">{site.uzmanlik} için doğrulanabilir saha planı ve teklif.</p></div><div><h3 className="font-bold text-[#22d3ee]">Kurumsal</h3><div className="mt-4 grid grid-cols-2 gap-3 text-[14px] text-[#cbd5e1]">{nav.slice(1).map(([h, e]) => <a href={h} key={h} className="hover:text-white">{e}</a>)}<a href={site.anaSite.url}>{site.anaSite.ad}</a></div></div><div><h3 className="font-bold text-[#22d3ee]">Teklif Hattı</h3><a href={`tel:${site.telefon}`} className="mt-4 flex gap-3"><Ikon ad="telefon" />{site.telefonGosterim}</a><a href={`mailto:${site.eposta}`} className="mt-3 flex gap-3 break-all"><Ikon ad="posta" />{site.eposta}</a></div></div></footer>
        <a href={`tel:${site.telefon}`} aria-label="Bilecik Platform'u ara" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#22d3ee] text-[#0f172a] shadow-xl"><Ikon ad="telefon" /></a>
    </div>;
}

function AnaSayfa({ site }: { site: SiteIcerik }) {
    return <><section className="relative min-h-[620px]"><Image src="/media/saha-hero.png" alt="Bilecik platform kiralama sahası" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-[#0f172a]/78" /><div className="relative mx-auto flex min-h-[620px] max-w-[1440px] items-center px-6 py-20"><div className="max-w-3xl text-white"><span className="rounded-full border border-[#22d3ee] px-4 py-2 text-[12px] font-bold tracking-[0.12em] text-[#22d3ee]">PROFESYONEL PLATFORM KİRALAMA</span><h1 className="mt-7 font-['Hanken_Grotesk'] text-[42px] font-extrabold leading-[48px] md:text-[56px] md:leading-[64px]">{site.h1}</h1><p className="mt-6 max-w-2xl text-[18px] leading-8 text-[#e2e8f0]">{site.paragraflar[0]}</p><div className="mt-8 flex flex-wrap gap-4"><a href="/iletisim" className="rounded-[8px] bg-[#22d3ee] px-7 py-4 font-bold text-[#0f172a]">Teklif İsteyin</a><a href="/urunler" className="rounded-[8px] border border-white px-7 py-4 font-bold">Filoyu İnceleyin</a></div></div></div></section>
        <section className="px-6 py-24"><div className="mx-auto max-w-[1440px]"><p className="text-[13px] font-bold uppercase tracking-[0.12em] text-[#0891b2]">Hizmet başlıkları</p><h2 className="mt-3 font-['Hanken_Grotesk'] text-[36px] font-extrabold">İşinize Uygun Erişim Çözümü</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{makineler.map((m) => <article key={m.baslik} className="group overflow-hidden rounded-[12px] border border-[#cbd5e1] bg-white"><div className="relative h-60"><Image src={m.gorsel} alt={m.baslik} fill sizes="33vw" className="object-cover transition-transform group-hover:scale-105" /></div><div className="p-7"><span className="text-[12px] font-bold text-[#0891b2]">{m.alt}</span><h3 className="mt-2 font-['Hanken_Grotesk'] text-[24px] font-bold">{m.baslik}</h3><p className="mt-3 leading-6 text-[#64748b]">{m.metin}</p><a href={`/${m.slug}`} className="mt-6 inline-flex items-center gap-2 font-bold text-[#0f172a]">Detayları İncele <Ikon ad="ok" /></a></div></article>)}</div></div></section>
        <section className="bg-[#0f172a] px-6 py-24 text-white"><div className="mx-auto grid max-w-[1440px] items-center gap-12 lg:grid-cols-2"><div><p className="text-[13px] font-bold uppercase tracking-[0.12em] text-[#22d3ee]">Güvenilir operasyon</p><h2 className="mt-3 font-['Hanken_Grotesk'] text-[36px] font-extrabold">İhtiyacınızı birlikte netleştirelim.</h2><p className="mt-5 leading-7 text-[#cbd5e1]">{site.paragraflar[1]}</p></div><div className="grid gap-4 sm:grid-cols-3">{["İşi tarif edin", "Uygunluğu kontrol edelim", "Yazılı teklif alın"].map((a, i) => <div key={a} className="rounded-[12px] bg-[#1e293b] p-6"><span className="text-[28px] font-extrabold text-[#22d3ee]">0{i + 1}</span><h3 className="mt-4 font-['Hanken_Grotesk'] text-[20px] font-bold">{a}</h3></div>)}</div></div></section></>;
}

function IcBaslik({ etiket, baslik, metin }: { etiket: string; baslik: string; metin?: string }) {
    return <section className="bg-[#e2e8f0] px-6 py-20"><div className="mx-auto max-w-[1440px]"><p className="text-[13px] font-bold tracking-[0.12em] text-[#0891b2]">{etiket}</p><h1 className="mt-4 max-w-4xl font-['Hanken_Grotesk'] text-[42px] font-extrabold leading-[50px]">{baslik}</h1>{metin && <p className="mt-5 max-w-2xl text-[18px] leading-7 text-[#475569]">{metin}</p>}</div></section>;
}
function Hakkimizda({ site }: { site: SiteIcerik }) {
    return <><IcBaslik etiket="KURUMSAL PROFİLİMİZ" baslik="Yerel Saha Bilgisi, Kurumsal İş Disiplini" metin={site.paragraflar[0]} /><section className="px-6 py-24"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-2"><div className="relative min-h-[480px] overflow-hidden rounded-[12px]"><Image src="/media/guvenli-calisma.png" alt="Bilecik güvenli platform operasyonu" fill sizes="50vw" className="object-cover" /></div><div>{site.paragraflar.slice(1).map((p) => <p key={p} className="mb-5 leading-7 text-[#475569]">{p}</p>)}<div className="mt-8 grid gap-4 sm:grid-cols-2">{["Misyonumuz", "Vizyonumuz"].map((b, i) => <article key={b} className="rounded-[12px] bg-[#f1f5f9] p-7"><h2 className="font-['Hanken_Grotesk'] text-[24px] font-bold">{b}</h2><p className="mt-3 text-[14px] leading-6 text-[#64748b]">{site.hizmetler[i]}</p></article>)}</div></div></div></section></>;
}
function Urunler() {
    return <><IcBaslik etiket="PLATFORM VE FORKLİFT ÇÖZÜMLERİ" baslik="Makine Filomuz" /><section className="px-6 py-24"><div className="mx-auto max-w-[1440px] space-y-8">{makineler.map((m, i) => <article key={m.baslik} className="grid overflow-hidden rounded-[12px] border border-[#cbd5e1] bg-white md:grid-cols-2"><div className={`relative min-h-[330px] ${i % 2 ? "md:order-2" : ""}`}><Image src={m.gorsel} alt={m.baslik} fill sizes="50vw" className="object-cover" /></div><div className="self-center p-10"><span className="text-[13px] font-bold text-[#0891b2]">{m.alt}</span><h2 className="mt-3 font-['Hanken_Grotesk'] text-[32px] font-extrabold">{m.baslik}</h2><p className="mt-4 leading-7 text-[#64748b]">{m.metin}</p><a href={`/${m.slug}`} className="mt-7 inline-flex rounded-[8px] bg-[#0f172a] px-6 py-3 font-bold text-white">Ürün Detayı</a></div></article>)}</div></section></>;
}
function Iletisim({ site }: { site: SiteIcerik }) {
    const opsiyonlar = site.bolge.split(",").map((x) => x.trim());
    return <><IcBaslik etiket="TEKLİF VE DESTEK HATTI" baslik="Saha Bilgilerinizi Paylaşın" metin="Çalışma yüksekliği, zemin, tarih ve adresi iletin; uygun makine sınıfını birlikte netleştirelim." /><section className="px-6 py-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[1fr_1.5fr]"><aside className="rounded-[12px] bg-[#0f172a] p-8 text-white"><h2 className="font-['Hanken_Grotesk'] text-[28px] font-bold">{site.h1}</h2><a href={`tel:${site.telefon}`} className="mt-8 flex gap-3 text-[20px]"><Ikon ad="telefon" />{site.telefonGosterim}</a><a href={`mailto:${site.eposta}`} className="mt-5 flex gap-3 break-all"><Ikon ad="posta" />{site.eposta}</a><p className="mt-5 flex gap-3 text-[#cbd5e1]"><Ikon ad="konum" />{site.bolge}</p></aside><div className="rounded-[12px] border border-[#cbd5e1] bg-white p-8"><TemaForm eposta={site.eposta} konu={`Bilecik Platform Teklif Talebi — ${site.h1}`} opsiyonlar={opsiyonlar} cls={{etiket:"mb-2 block text-[14px] font-bold text-[#0f172a]",alan:"w-full rounded-[8px] border border-[#cbd5e1] bg-[#f8fafc] p-3 outline-none focus:border-[#0891b2]",buton:"w-full rounded-[8px] bg-[#0f172a] px-7 py-4 font-bold text-white",izgara:"grid gap-5 md:grid-cols-2"}} /></div></div></section></>;
}
function BlogListe({ site }: { site: SiteIcerik }) {
    return <><IcBaslik etiket="SEKTÖREL BİLGİLER VE REHBERLER" baslik="Saha Odaklı Planlama ve Güvenlik Rehberi" /><section className="px-6 py-24"><div className="mx-auto grid max-w-[1440px] gap-7 md:grid-cols-2">{hostBloglari(site.host).map((y) => <article key={y.slug} className="grid overflow-hidden rounded-[12px] border border-[#cbd5e1] bg-white sm:grid-cols-[220px_1fr]"><div className="relative min-h-[220px]"><Image src={y.gorsel} alt={y.gorselAlt} fill sizes="220px" className="object-cover" /></div><div className="p-6"><span className="text-[12px] font-bold text-[#0891b2]">{y.kategori}</span><h2 className="mt-2 font-['Hanken_Grotesk'] text-[22px] font-bold">{y.baslik}</h2><p className="mt-3 line-clamp-2 text-[14px] leading-6 text-[#64748b]">{y.ozet}</p><a href={`/blog/${y.slug}`} className="mt-5 inline-flex items-center gap-2 font-bold">Rehberi Oku <Ikon ad="ok" /></a></div></article>)}</div></section></>;
}

export const bilecikTema: TemaModulu = { Cerceve, AnaSayfa, sayfalar: { hakkimizda: Hakkimizda, iletisim: Iletisim, urunler: Urunler }, BlogListe };
