import Image from "next/image";
import { hostBloglari } from "@/lib/blog";
import type { SiteIcerik } from "@/lib/siteler";
import { TemaForm } from "./tema-form";
import type { TemaModulu } from "./tipler";

const yollar = { ok: "M5 12h14M13 5l7 7-7 7", telefon: "M22 16.92v3a2 2 0 0 1-2.18 2A19.79 19.79 0 0 1 3.09 5.18 2 2 0 0 1 5.08 3h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L9.06 10.91a16 16 0 0 0 4 4l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z", posta: "M4 4h16v16H4zM22 6l-10 7L2 6", konum: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1 1 18 0zM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z", onay: "M20 6L9 17l-5-5" };
function Ikon({ ad, className = "h-5 w-5" }: { ad: keyof typeof yollar; className?: string }) { return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={yollar[ad]} /></svg>; }
const urunler = [
    { baslik: "Makaslı Platformlar", metin: "OSB tesislerinde düz zemin, raf, aydınlatma ve hat üstü bakım.", gorsel: "/media/makasli-platform.png", slug: "makasli-platform-kiralama" },
    { baslik: "Eklemli & Teleskopik Platformlar", metin: "Baca, kanal, cephe ve üretim engellerinin arkasına erişim.", gorsel: "/media/eklemli-platform.png", slug: "eklemli-ve-teleskopik-platform-kiralama" },
    { baslik: "Yüksek Erişim Çözümleri", metin: "Açık saha, çelik montaj ve uzun erişim gerektiren proje işleri.", gorsel: "/media/blog/celik-konstruksiyon-montaji-makasli-platform-forklift-kiralama.jpg", slug: "eklemli-ve-teleskopik-platform-kiralama" },
];
function Cerceve({ site, aktif = "", children }: Parameters<TemaModulu["Cerceve"]>[0]) {
    const nav = [["/", "Ana Sayfa"], ["/hakkimizda", "Kurumsal"], ["/urunler", "Ürünler"], ["/blog", "Blog"], ["/iletisim", "İletişim"]];
    return <div className="min-h-screen bg-[#faf6f0] text-[#2e3230] font-['Nunito_Sans']">
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Literata:wght@500;600;700&family=Nunito+Sans:wght@400;500;600;700&display=swap" />
        <header className="sticky top-0 z-50 bg-[#faf6f0]/95 shadow-[0_4px_20px_rgba(46,50,48,0.06)] backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><a href="/" className="flex items-center gap-3"><Image src="/media/logo/4.png" alt={`${site.h1} logosu`} width={48} height={48} className="h-10 w-auto object-contain" /><span className="font-['Literata'] text-[20px] font-bold text-[#4a7c59]">Bozüyük Platform</span></a><nav className="hidden items-center gap-3 lg:flex">{nav.map(([h, e]) => <a key={h} href={h} className={`rounded-[8px] px-3 py-2 font-semibold ${aktif === h ? "bg-[#c8e8d0] text-[#2a6038]" : "text-[#4a4e4a] hover:bg-[#f5f1ea] hover:text-[#4a7c59]"}`}>{e}</a>)}</nav><a href="/iletisim" className="rounded-[8px] bg-[#4a7c59] px-5 py-3 font-bold text-white">Teklif Alın</a></div></header>
        <main>{children}</main>
        <footer className="bg-[#2e3230] px-6 py-16 text-[#f5f0e8]"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><h2 className="font-['Literata'] text-[24px] font-bold">Bozüyük Platform</h2><p className="mt-4 leading-6 text-[#d4ccbf]">{site.uzmanlik} için yerel planlama ve doğrulanmış teklif.</p></div><div><h3 className="font-['Literata'] text-[18px] font-semibold text-[#8ecf9e]">Bağlantılar</h3><div className="mt-4 grid grid-cols-2 gap-3">{nav.slice(1).map(([h, e]) => <a key={h} href={h}>{e}</a>)}<a href={site.anaSite.url}>{site.anaSite.ad}</a></div></div><div><h3 className="font-['Literata'] text-[18px] font-semibold text-[#8ecf9e]">Bize Ulaşın</h3><a className="mt-4 flex gap-3" href={`tel:${site.telefon}`}><Ikon ad="telefon" />{site.telefonGosterim}</a><a className="mt-3 flex gap-3 break-all" href={`mailto:${site.eposta}`}><Ikon ad="posta" />{site.eposta}</a></div></div></footer>
        <a href={`tel:${site.telefon}`} aria-label="Bozüyük Platform'u ara" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-full bg-[#4a7c59] text-white shadow-xl"><Ikon ad="telefon" /></a>
    </div>;
}
function AnaSayfa({ site }: { site: SiteIcerik }) {
    return <div className="pb-16 pt-8"><section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-16 pt-8 lg:grid-cols-2 lg:px-8"><div><div className="mb-6 inline-flex rounded-full bg-[#c8e8d0] px-4 py-2 text-[12px] font-bold tracking-[0.1em] text-[#2a6038]">BOZÜYÜK OSB SAHA ÇÖZÜMLERİ</div><h1 className="font-['Literata'] text-[48px] font-bold leading-tight text-[#2e3230] lg:text-[60px]">{site.h1}<br /><span className="text-[#4a7c59]">Planlı ve Güvenli.</span></h1><p className="mt-6 text-[18px] leading-8 text-[#4a4e4a]">{site.paragraflar[0]}</p><div className="mt-8 flex flex-wrap gap-4"><a href="/iletisim" className="rounded-[12px] bg-[#4a7c59] px-7 py-4 font-bold text-white">Saha Talebi Oluştur</a><a href="/urunler" className="rounded-[12px] border border-[#4a7c59] bg-[#f5f1ea] px-7 py-4 font-bold text-[#4a7c59]">Ürünleri İncele</a></div></div><div className="relative min-h-[560px] overflow-hidden rounded-[24px] shadow-[0_4px_20px_rgba(46,50,48,0.06)]"><Image src="/media/saha-hero.png" alt="Bozüyük OSB platform kiralama" fill priority sizes="50vw" className="object-cover" /></div></section>
        <section className="mx-4 mt-12 rounded-[24px] bg-[#f5f1ea] px-6 py-20 shadow-[0_4px_20px_rgba(46,50,48,0.06)] lg:mx-auto lg:max-w-7xl lg:px-8"><div className="mb-12 max-w-2xl"><h2 className="font-['Literata'] text-[40px] font-bold text-[#2e3230]">Planlı Saha Çözümü</h2><p className="mt-4 leading-7 text-[#4a4e4a]">{site.paragraflar[1]}</p></div><div className="grid gap-8 md:grid-cols-3">{["İhtiyaç Analizi", "Uygunluk Kontrolü", "Yazılı Kapsam"].map((b, i) => <article key={b}><div className="mb-6 flex h-14 w-14 items-center justify-center rounded-[16px] bg-[#c8e8d0] font-['Literata'] text-[22px] font-bold text-[#2a6038]">0{i + 1}</div><h3 className="font-['Literata'] text-[24px] font-bold text-[#2e3230]">{b}</h3><p className="mt-3 leading-7 text-[#4a4e4a]">{site.paragraflar[Math.min(i + 1, site.paragraflar.length - 1)]}</p></article>)}</div></section>
        <section className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><div className="mb-12"><h2 className="font-['Literata'] text-[40px] font-bold text-[#2e3230]">Hizmet Başlıkları</h2><p className="mt-4 max-w-2xl text-[#4a4e4a]">Bozüyük Organize Sanayi Bölgesi ve çevresi için sahaya göre seçilen erişim sınıfları.</p></div><div className="grid gap-8 md:grid-cols-2">{urunler.slice(0, 2).map((u) => <article key={u.baslik} className="group"><div className="relative h-[420px] overflow-hidden rounded-[24px]"><Image src={u.gorsel} alt={u.baslik} fill sizes="50vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /></div><h3 className="mt-6 font-['Literata'] text-[30px] font-bold text-[#2e3230]">{u.baslik}</h3><p className="mt-2 leading-7 text-[#4a4e4a]">{u.metin}</p><a href={`/${u.slug}`} className="mt-5 inline-flex items-center gap-2 font-bold text-[#4a7c59]">Detaylar <Ikon ad="ok" /></a></article>)}</div></section>
        <section className="mt-12 rounded-t-[48px] border-t border-[#c4c8bc]/30 bg-[#e4e0d8] px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1fr_1.4fr]"><div><h2 className="font-['Literata'] text-[40px] font-bold text-[#2e3230]">İhtiyacınızı birlikte netleştirelim.</h2><p className="mt-6 leading-7 text-[#4a4e4a]">{site.paragraflar[2]}</p><a href="/iletisim" className="mt-8 inline-flex rounded-[12px] bg-[#4a7c59] px-7 py-4 font-bold text-white">Teklif Hazırlayın</a></div><div className="space-y-5">{["İşi tarif edin", "Uygunluğu kontrol edelim", "Yazılı teklif alın"].map((a, i) => <article key={a} className="rounded-[16px] bg-[#faf6f0] p-6"><span className="text-[12px] font-bold text-[#4a7c59]">0{i + 1}</span><h3 className="mt-2 font-['Literata'] text-[20px] font-bold text-[#2e3230]">{a}</h3></article>)}</div></div></section></div>;
}
function Baslik({ ust, baslik, aciklama }: { ust: string; baslik: string; aciklama?: string }) { return <section className="bg-[#f0ece4] px-6 py-20"><div className="mx-auto max-w-7xl"><p className="font-bold tracking-[0.1em] text-[#4a7c59]">{ust}</p><h1 className="mt-3 font-['Literata'] text-[42px] font-bold">{baslik}</h1>{aciklama && <p className="mt-5 max-w-3xl text-[18px] leading-8 text-[#4a4e4a]">{aciklama}</p>}</div></section>; }
function Hakkimizda({ site }: { site: SiteIcerik }) { return <main className="mx-auto flex max-w-7xl flex-col gap-16 px-6 pb-16 pt-24 md:px-12"><header className="relative flex min-h-[410px] items-center overflow-hidden rounded-[24px] bg-[#e4e0d8] p-8 shadow-[0_4px_20px_rgba(46,50,48,0.06)] md:p-16"><div className="relative z-10 max-w-2xl"><span className="font-bold tracking-[0.1em] text-[#4a7c59]">KURUMSAL</span><h1 className="mt-4 font-['Literata'] text-[48px] font-bold leading-tight text-[#2e3230] md:text-[60px]">Yerel Kökler,<br /><span className="text-[#4a7c59]">Güvenilir Çözümler.</span></h1></div><Image src="/media/guvenli-calisma.png" alt="Bozüyük platform kurumsal saha" fill sizes="100vw" className="object-cover opacity-20" /></header><section className="grid gap-6 md:grid-cols-12"><article className="rounded-[32px] bg-[#f5f1ea] p-8 shadow-[0_4px_20px_rgba(46,50,48,0.06)] md:col-span-8 md:p-12"><h2 className="font-['Literata'] text-[32px] font-bold">Hakkımızda</h2>{site.paragraflar.map((p) => <p key={p} className="mt-5 leading-7 text-[#4a4e4a]">{p}</p>)}</article><article className="relative overflow-hidden rounded-[32px] bg-[#4a7c59] p-8 text-white md:col-span-4"><h3 className="font-['Literata'] text-[26px] font-bold">Bozüyük OSB Köklerimiz</h3><p className="mt-4 leading-7 text-[#d8f0de]">{site.uzmanlik} odağında yerel saha bilgisini operasyon planına dönüştürüyoruz.</p><Ikon ad="konum" className="absolute -bottom-8 -right-8 h-40 w-40 text-white/10" /></article><article className="rounded-[32px] border border-[#c4c8bc]/20 bg-[#f0ece4] p-8 md:col-span-6"><h3 className="font-['Literata'] text-[26px] font-bold">Vizyonumuz</h3><p className="mt-4 leading-7 text-[#4a4e4a]">{site.hizmetler[0]}</p></article><article className="rounded-[32px] border border-[#c4c8bc]/20 bg-[#f0ece4] p-8 md:col-span-6"><h3 className="font-['Literata'] text-[26px] font-bold">Misyonumuz</h3><p className="mt-4 leading-7 text-[#4a4e4a]">{site.hizmetler[1]}</p></article></section><section className="rounded-[40px] border border-[#c4c8bc]/30 bg-[#e4e0d8] p-8 shadow-[0_4px_20px_rgba(46,50,48,0.06)] md:p-12"><h2 className="font-['Literata'] text-[36px] font-bold">Kalite Politikası</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{site.hizmetler.slice(2).map((h) => <div key={h} className="rounded-[16px] bg-[#faf6f0] p-6"><span className="text-[#4a7c59]"><Ikon ad="onay" /></span><p className="mt-3 leading-6">{h}</p></div>)}</div></section></main>; }
function Urunler() { return <><Baslik ust="SAHA EKİPMANLARI" baslik="Ürünlerimiz" /><section className="px-6 py-24"><div className="mx-auto grid max-w-7xl gap-7 md:grid-cols-3">{urunler.map((u) => <article key={u.baslik} className="overflow-hidden rounded-[24px] border border-[#c4c8bc] bg-white"><div className="relative h-72"><Image src={u.gorsel} alt={u.baslik} fill sizes="33vw" className="object-cover" /></div><div className="p-7"><h2 className="font-['Literata'] text-[24px] font-bold">{u.baslik}</h2><p className="mt-3 leading-6 text-[#4a4e4a]">{u.metin}</p><a href={`/${u.slug}`} className="mt-6 flex items-center justify-center rounded-[8px] bg-[#4a7c59] px-6 py-3 font-bold text-white">Ürünü İncele</a></div></article>)}</div></section></>; }
function Iletisim({ site }: { site: SiteIcerik }) { const bolgeler = site.bolge.split(",").map((x) => x.trim()); return <main className="mx-auto flex max-w-7xl flex-col gap-16 px-6 py-20"><header className="mx-auto max-w-3xl text-center"><h1 className="font-['Literata'] text-[48px] leading-tight">Bizimle İletişime Geçin</h1><p className="mt-5 text-[18px] leading-8 text-[#4a4e4a]">Saha ölçülerini, çalışma tarihini ve erişim ihtiyacını iletin.</p></header><div className="grid gap-8 md:grid-cols-3">{[["telefon", "Telefon", site.telefonGosterim, `tel:${site.telefon}`], ["posta", "E-posta", site.eposta, `mailto:${site.eposta}`], ["konum", "Merkez Ofis & Garaj", site.bolge, "/iletisim"]].map(([i, b, m, h]) => <a key={b} href={h} className="rounded-[24px] bg-[#f5f1ea] p-8 text-center shadow-[0_4px_20px_rgba(46,50,48,0.06)]"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#c8e8d0] text-[#4a7c59]"><Ikon ad={i as keyof typeof yollar} /></span><h3 className="mt-5 font-['Literata'] text-[22px]">{b}</h3><p className="mt-2 break-all text-[#4a4e4a]">{m}</p></a>)}</div><div className="mx-auto w-full max-w-4xl rounded-[24px] bg-white p-8 shadow-[0_4px_20px_rgba(46,50,48,0.06)]"><h2 className="mb-8 font-['Literata'] text-[28px]">Bize Mesaj Gönderin</h2><TemaForm eposta={site.eposta} konu={`Bozüyük Platform Teklif Talebi — ${site.h1}`} opsiyonlar={bolgeler} cls={{etiket:"mb-2 block font-semibold text-[#2e3230]",alan:"w-full rounded-[8px] border border-[#c4c8bc] bg-[#faf6f0] p-3 outline-none focus:border-[#4a7c59]",buton:"w-full rounded-[12px] bg-[#4a7c59] px-7 py-4 font-bold text-white",izgara:"grid gap-5 md:grid-cols-2"}} /></div></main>; }
function BlogListe({ site }: { site: SiteIcerik }) { const yazilar = hostBloglari(site.host); const ilk = yazilar[0]; return <main className="mx-auto w-full max-w-7xl px-6 pb-16 pt-24 md:px-8"><section className="mx-auto mb-16 max-w-3xl text-center"><h1 className="font-['Literata'] text-[40px] font-bold leading-tight md:text-[52px]">Endüstriyel Çözümler ve Güvenlik Rehberi</h1><p className="mt-5 text-[#4a4e4a]">Saha planlaması, makine seçimi ve iş güvenliği için yerel rehberler.</p></section>{ilk && <section className="mb-16 grid overflow-hidden rounded-[24px] bg-white shadow-[0_4px_20px_rgba(46,50,48,0.06)] md:grid-cols-2"><div className="relative min-h-[380px]"><Image src={ilk.gorsel} alt={ilk.gorselAlt} fill sizes="50vw" className="object-cover" /></div><div className="self-center p-10"><span className="text-[12px] font-bold text-[#4a7c59]">{ilk.kategori}</span><h2 className="mt-3 font-['Literata'] text-[32px] font-bold">{ilk.baslik}</h2><p className="mt-4 line-clamp-4 leading-7 text-[#4a4e4a]">{ilk.ozet}</p><a href={`/blog/${ilk.slug}`} className="mt-6 inline-flex items-center gap-2 font-bold text-[#4a7c59]">Yazıyı Oku <Ikon ad="ok" /></a></div></section>}<section className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{yazilar.slice(1).map((y) => <article key={y.slug} className="flex flex-col overflow-hidden rounded-[16px] border border-[#c4c8bc]/20 bg-white shadow-[0_4px_20px_rgba(46,50,48,0.06)]"><div className="relative h-56"><Image src={y.gorsel} alt={y.gorselAlt} fill sizes="33vw" className="object-cover" /></div><div className="flex flex-1 flex-col p-6"><span className="text-[12px] font-bold text-[#4a7c59]">{y.kategori}</span><h3 className="mt-2 font-['Literata'] text-[21px] font-semibold">{y.baslik}</h3><p className="mt-3 line-clamp-3 flex-1 text-[14px] leading-6 text-[#4a4e4a]">{y.ozet}</p><a href={`/blog/${y.slug}`} className="mt-5 inline-flex items-center gap-2 font-bold text-[#4a7c59]">Devamını Oku <Ikon ad="ok" /></a></div></article>)}</section><section className="mt-20 flex flex-col items-center justify-between gap-6 rounded-[16px] bg-[#78a886] p-8 text-[#d8f0de] md:flex-row md:p-12"><div><h3 className="font-['Literata'] text-[26px] font-bold">Sektörel Gelişmelerden Haberdar Olun</h3><p className="mt-2">Güncel saha rehberlerini ve kiralama bilgilerini takip edin.</p></div><a href="/iletisim" className="rounded-[12px] bg-[#4a7c59] px-6 py-3 font-bold text-white">Bize Ulaşın</a></section></main>; }
export const bozuyukTema: TemaModulu = { Cerceve, AnaSayfa, sayfalar: { hakkimizda: Hakkimizda, iletisim: Iletisim, urunler: Urunler }, BlogListe };
