import Image from "next/image";
import { hostBloglari } from "@/lib/blog";
import type { SiteIcerik } from "@/lib/siteler";
import { TemaForm } from "./tema-form";
import type { TemaModulu } from "./tipler";

const yollar = { ok: "M5 12h14M13 5l7 7-7 7", telefon: "M22 16.92v3a2 2 0 0 1-2.18 2A19.79 19.79 0 0 1 3.09 5.18 2 2 0 0 1 5.08 3h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L9.06 10.91a16 16 0 0 0 4 4l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z", posta: "M4 4h16v16H4zM22 6l-10 7L2 6", konum: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1 1 18 0zM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z", onay: "M20 6L9 17l-5-5", saat: "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM12 6v6l4 2" };
function Ikon({ ad, className = "h-5 w-5" }: { ad: keyof typeof yollar; className?: string }) { return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={yollar[ad]} /></svg>; }
const urunler = [
    { baslik: "Makaslı Platformlar", metin: "Fabrika, depo ve liman tesislerinde 8–18 metre dikey erişim.", gorsel: "/media/makasli-platform.png", slug: "makasli-platform-kiralama" },
    { baslik: "Eklemli & Teleskopik", metin: "Enerji tesisi, cephe ve çelik konstrüksiyonda engel aşan erişim.", gorsel: "/media/eklemli-platform.png", slug: "eklemli-ve-teleskopik-platform-kiralama" },
    { baslik: "Yüksek Erişim Platformları", metin: "Rüzgâr, zemin ve saha giriş koşulları doğrulanarak proje planı.", gorsel: "/media/blog/celik-konstruksiyon-montaji-makasli-platform-forklift-kiralama.jpg", slug: "eklemli-ve-teleskopik-platform-kiralama" },
];
function Cerceve({ site, aktif = "", children }: Parameters<TemaModulu["Cerceve"]>[0]) {
    const nav = [["/", "Ana Sayfa"], ["/hakkimizda", "Hakkımızda"], ["/urunler", "Ürünler"], ["/blog", "Blog"], ["/iletisim", "İletişim"]];
    return <div className="min-h-screen bg-[#f8f9fa] text-[#191c1d] font-['Inter']">
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Montserrat:wght@600;700;800&display=swap" />
        <header className="sticky top-0 z-50 border-b-2 border-[#936e6a]/20 bg-[#f8f9fa]/80 shadow-sm backdrop-blur-md"><div className="mx-auto flex max-w-[1280px] items-center justify-between px-4 py-4 md:px-6"><a href="/" className="flex items-center gap-3"><Image src="/media/logo/logo.png" alt={`${site.h1} logosu`} width={145} height={40} className="h-10 w-auto object-contain" /><span className="hidden font-['Montserrat'] text-[19px] font-extrabold text-[#1A1C1E] sm:block">Çanakkale Platform</span></a><nav className="hidden items-center gap-1 lg:flex">{nav.map(([h, e]) => <a key={h} href={h} className={`border-b-2 px-4 py-3 text-[14px] font-bold ${aktif === h ? "border-[#ed1c24] text-[#bb0013]" : "border-transparent text-[#595c5f] hover:text-[#1A1C1E]"}`}>{e}</a>)}</nav><a href={`tel:${site.telefon}`} className="rounded-[2px] border-b-2 border-[#93000d] bg-[#ed1c24] px-5 py-3 text-[14px] font-bold text-white">Saha Hattı</a></div></header>
        <main>{children}</main>
        <footer className="border-t-4 border-[#ed1c24] bg-[#1A1C1E] px-6 py-14 text-white"><div className="mx-auto grid max-w-[1280px] gap-10 md:grid-cols-3"><div><h2 className="font-['Montserrat'] text-[24px] font-bold">Çanakkale Platform</h2><p className="mt-4 text-[14px] leading-6 text-[#c4c7ca]">{site.uzmanlik} için endüstriyel kiralama ve sevkiyat planı.</p></div><div><h3 className="font-bold uppercase tracking-[0.1em] text-[#ed1c24]">Hızlı Erişim</h3><div className="mt-4 grid grid-cols-2 gap-3 text-[14px]">{nav.slice(1).map(([h, e]) => <a key={h} href={h}>{e}</a>)}<a href={site.anaSite.url}>{site.anaSite.ad}</a></div></div><div><h3 className="font-bold uppercase tracking-[0.1em] text-[#ed1c24]">İletişim</h3><a className="mt-4 flex gap-3" href={`tel:${site.telefon}`}><Ikon ad="telefon" />{site.telefonGosterim}</a><a className="mt-3 flex gap-3 break-all" href={`mailto:${site.eposta}`}><Ikon ad="posta" />{site.eposta}</a></div></div></footer>
        <a href={`tel:${site.telefon}`} aria-label="Çanakkale Platform'u ara" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-[8px] bg-[#ed1c24] text-white shadow-xl"><Ikon ad="telefon" /></a>
    </div>;
}
function AnaSayfa({ site }: { site: SiteIcerik }) { return <><section className="border-b-4 border-[#ed1c24] bg-white"><div className="mx-auto grid max-w-[1280px] items-stretch md:grid-cols-2"><div className="flex flex-col justify-center px-6 py-16 md:px-16 md:py-24"><span className="mb-5 text-[12px] font-bold uppercase tracking-[0.08em] text-[#bb0013]">ÇANAKKALE • BİGA • ÇAN • GELİBOLU</span><h1 className="font-['Montserrat'] text-[36px] font-extrabold uppercase leading-tight tracking-tight text-[#1A1C1E] md:text-[48px] md:leading-[56px]">{site.h1}<br /><span className="text-[#ed1c24]">Saha Odaklı Çözüm</span></h1><p className="mt-6 text-[18px] leading-7 text-[#5e3f3c]">{site.paragraflar[0]}</p><div className="mt-8 flex flex-wrap gap-4"><a href="/iletisim" className="rounded-[2px] border-b-2 border-[#93000d] bg-[#ed1c24] px-8 py-4 font-bold text-white">Teklif Oluşturun</a><a href="/urunler" className="rounded-[2px] border-2 border-[#1A1C1E] px-8 py-4 font-bold text-[#1A1C1E]">Makine Sınıfları</a></div></div><div className="relative min-h-[560px]"><Image src="/media/saha-hero.png" alt="Çanakkale endüstriyel platform kiralama sahası" fill priority sizes="50vw" className="object-cover" /><div className="absolute bottom-0 left-0 bg-[#1A1C1E] px-6 py-4 font-['JetBrains_Mono'] text-[12px] font-medium text-white">SAHA TESLİMATINA HAZIR • UYGUNLUK KONTROLLÜ</div></div></div></section><section className="bg-[#f3f4f5] px-6 py-10"><div className="mx-auto grid max-w-[1280px] gap-6 md:grid-cols-3">{site.hizmetler.slice(0, 3).map((h, i) => <article key={h} className="flex gap-4 border-l-4 border-[#ed1c24] bg-white p-6"><span className="font-['Montserrat'] text-[28px] font-extrabold text-[#ed1c24]">0{i + 1}</span><p className="font-semibold leading-6">{h}</p></article>)}</div></section></>; }
function Baslik({ ust, baslik, metin }: { ust: string; baslik: string; metin?: string }) { return <section className="relative overflow-hidden bg-[#1A1C1E] px-6 py-20 text-white"><div className="absolute right-0 top-0 h-full w-1/3 -skew-x-12 bg-[#ed1c24]/15" /><div className="relative mx-auto max-w-[1280px]"><p className="text-[13px] font-bold tracking-[0.14em] text-[#ffb4ab]">{ust}</p><h1 className="mt-4 max-w-4xl font-['Montserrat'] text-[42px] font-extrabold leading-[50px]">{baslik}</h1>{metin && <p className="mt-5 max-w-3xl text-[18px] leading-8 text-[#c4c7ca]">{metin}</p>}</div></section>; }
function Hakkimizda({ site }: { site: SiteIcerik }) { return <main className="mx-auto w-full max-w-[1280px] px-6 py-24"><section className="grid items-center gap-12 lg:grid-cols-2"><div><span className="text-[12px] font-bold tracking-[0.08em] text-[#ed1c24]">HAKKIMIZDA</span><h1 className="mt-4 font-['Montserrat'] text-[48px] font-extrabold leading-[56px] text-[#1A1C1E]">Endüstriyel Güven ve Yerel Tecrübe.</h1><p className="mt-6 text-[18px] leading-8 text-[#5e3f3c]">{site.paragraflar[0]}</p>{site.paragraflar.slice(1).map((p) => <p key={p} className="mt-5 leading-7 text-[#5e3f3c]">{p}</p>)}<ul className="mt-7 grid gap-4 sm:grid-cols-2">{site.hizmetler.map((h) => <li key={h} className="flex gap-3 border-l-4 border-[#ed1c24] bg-[#f3f4f5] p-4 font-semibold"><Ikon ad="onay" className="h-5 w-5 text-[#ed1c24]" />{h}</li>)}</ul></div><div className="relative min-h-[600px] overflow-hidden rounded-[4px]"><Image src="/media/guvenli-calisma.png" alt="Çanakkale güvenli saha operasyonu" fill sizes="50vw" className="object-cover" /><div className="absolute bottom-0 left-0 right-0 border-t-4 border-[#ed1c24] bg-[#1A1C1E] p-6 text-white"><strong className="font-['Montserrat'] uppercase">Planlı Operasyon • Doğrulanmış Kapsam</strong></div></div></section></main>; }
function Urunler() { return <main className="mx-auto w-full max-w-[1280px] px-6 py-12"><header className="mb-12 max-w-4xl"><span className="text-[12px] font-bold tracking-[0.08em] text-[#ed1c24]">ÜRÜNLERİMİZ</span><h1 className="mt-4 font-['Montserrat'] text-[48px] font-extrabold leading-[56px] text-[#1A1C1E]">Saha Odaklı Endüstriyel Kiralama Çözümleri</h1></header><section className="grid grid-cols-1 gap-6 md:grid-cols-12">{urunler.map((u, i) => <article key={u.baslik} className={`group flex border border-[#1A1C1E] bg-white transition-colors hover:border-[#ed1c24] ${i === 0 ? "flex-col md:col-span-8 md:flex-row" : i === 1 ? "flex-col md:col-span-4" : "flex-col md:col-span-12 md:flex-row-reverse"}`}><div className={`relative ${i === 1 ? "h-64" : "min-h-[340px] flex-1"}`}><Image src={u.gorsel} alt={u.baslik} fill sizes={i === 1 ? "33vw" : "60vw"} className="object-cover" /></div><div className="flex flex-1 flex-col justify-center p-8"><span className="font-['JetBrains_Mono'] text-[12px] font-bold text-[#ed1c24]">0{i + 1} / SAHA EKİPMANI</span><h2 className="mt-3 font-['Montserrat'] text-[24px] font-bold text-[#1A1C1E] md:text-[32px]">{u.baslik}</h2><p className="mt-4 leading-7 text-[#5e3f3c]">{u.metin}</p><div className="mt-6 grid grid-cols-2 gap-4 border-y border-[#d9dadb] py-4 font-['JetBrains_Mono'] text-[12px]"><span>YÜKSEKLİK<br /><b>SAHAYA GÖRE</b></span><span>UYGUNLUK<br /><b>TEKLİFTE TEYİT</b></span></div><a href={`/${u.slug}`} className="mt-7 inline-flex w-fit rounded-[2px] bg-[#ed1c24] px-7 py-4 font-bold text-white">Detay Sayfası</a></div></article>)}</section></main>; }
function Iletisim({ site }: { site: SiteIcerik }) { const bolgeler = site.bolge.split(",").map((x) => x.trim()); return <><Baslik ust="İLETİŞİM" baslik="Saha İletişim & Talep" metin="Teknik görev bilgilerini paylaşın; makine, nakliye ve saha giriş kapsamını netleştirelim." /><section className="px-6 py-24"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_1.5fr]"><aside className="rounded-[4px] bg-[#1A1C1E] p-8 text-white"><h2 className="font-['Montserrat'] text-[24px] font-bold">Acil Saha Destek & Kiralama</h2><a className="mt-8 flex gap-3 text-[20px]" href={`tel:${site.telefon}`}><Ikon ad="telefon" />{site.telefonGosterim}</a><a className="mt-5 flex gap-3 break-all" href={`mailto:${site.eposta}`}><Ikon ad="posta" />{site.eposta}</a><p className="mt-5 flex gap-3 text-[#c4c7ca]"><Ikon ad="konum" />{site.bolge}</p><p className="mt-5 flex gap-3 text-[#c4c7ca]"><Ikon ad="saat" />Hafta içi 08.00–18.00</p></aside><div className="rounded-[4px] border border-[#d9dadb] bg-white p-8"><h2 className="mb-6 font-['Montserrat'] text-[26px] font-bold">Saha İhtiyaç Formu</h2><TemaForm eposta={site.eposta} konu={`Çanakkale Platform Teklif Talebi — ${site.h1}`} opsiyonlar={bolgeler} cls={{etiket:"mb-2 block text-[14px] font-bold text-[#1A1C1E]",alan:"w-full rounded-[2px] border border-[#936e6a] bg-[#f8f9fa] p-3 outline-none focus:border-[#ed1c24]",buton:"w-full rounded-[2px] bg-[#ed1c24] px-8 py-4 font-bold text-white",izgara:"grid gap-5 md:grid-cols-2"}} /></div></div></section></>; }
function BlogListe({ site }: { site: SiteIcerik }) { const yazilar = hostBloglari(site.host); const adimlar = ["İşi Geometrik Olarak Tarif Edin", "Makine Sınıfını İşin Hareketine Göre Seçin", "Zemin Uygunluğunu Önden Teyit Edin"]; return <main className="pb-24"><section className="mx-auto grid max-w-[1280px] items-center gap-6 px-6 py-12 md:grid-cols-12 md:py-24"><div className="md:col-span-7"><span className="text-[12px] font-bold tracking-[0.08em] text-[#ed1c24]">BLOG VE REHBER</span><h1 className="mt-4 font-['Montserrat'] text-[36px] font-extrabold leading-tight text-[#1A1C1E] md:text-[48px]">Saha Planlaması, Güvenlik ve Makine Seçimi</h1><p className="mt-5 max-w-2xl text-[18px] leading-7 text-[#5e3f3c]">Çanakkale&apos;de doğru platform sınıfı ve güvenli saha planı için karar rehberi.</p></div><div className="relative min-h-[360px] md:col-span-5"><Image src={yazilar[0]?.gorsel ?? "/media/saha-hero.png"} alt={yazilar[0]?.gorselAlt ?? "Çanakkale saha rehberi"} fill sizes="40vw" className="object-cover" /></div></section><section className="border-y border-[#936e6a]/20 bg-[#f3f4f5] py-16"><div className="mx-auto max-w-[1280px] px-6"><h2 className="inline-block border-b-2 border-[#1A1C1E] pb-4 font-['Montserrat'] text-[32px] font-bold text-[#1A1C1E]">Karar Rehberi</h2><div className="mt-10 space-y-0">{adimlar.map((a, i) => { const y = yazilar[i]; return <article key={a} className="grid gap-6 border-b border-[#936e6a]/20 py-8 md:grid-cols-[100px_1fr_220px]"><span className="font-['Montserrat'] text-[48px] font-extrabold text-[#e1e3e4]">0{i + 1}</span><div><h3 className="font-['Montserrat'] text-[18px] font-semibold uppercase tracking-tight text-[#1A1C1E]">{a}</h3><p className="mt-3 leading-7 text-[#5e3f3c]">{y?.ozet ?? site.paragraflar[i]}</p></div>{y && <a href={`/blog/${y.slug}`} className="self-center justify-self-start rounded-[2px] border-2 border-[#1A1C1E] px-5 py-3 font-bold text-[#1A1C1E] md:justify-self-end">Yazıyı Oku</a>}</article>; })}</div></div></section></main>; }
export const canakkaleTema: TemaModulu = { Cerceve, AnaSayfa, sayfalar: { hakkimizda: Hakkimizda, iletisim: Iletisim, urunler: Urunler }, BlogListe };
