import Image from "next/image";
import { hostBloglari } from "@/lib/blog";
import type { SiteIcerik } from "@/lib/siteler";
import { TemaForm } from "./tema-form";
import type { TemaModulu } from "./tipler";

function Ikon({ ad, className = "h-5 w-5" }: { ad: keyof typeof yollar; className?: string }) {
    return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={yollar[ad]} /></svg>;
}

const yollar = {
    ok: "M5 12h14M13 5l7 7-7 7",
    telefon: "M22 16.92v3a2 2 0 0 1-2.18 2A19.79 19.79 0 0 1 3.09 5.18 2 2 0 0 1 5.08 3h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L9.06 10.91a16 16 0 0 0 4 4l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z",
    posta: "M4 4h16v16H4zM22 6l-10 7L2 6",
    konum: "M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 1 1 18 0zM12 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z",
    onay: "M20 6L9 17l-5-5",
    saat: "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM12 6v6l4 2",
};

const urunler = [
    { baslik: "Makaslı Platformlar", metin: "Düz ve taşıyıcı zeminlerde fabrika, depo ve tesis içi dikey erişim.", gorsel: "/media/makasli-platform.png", slug: "makasli-platform-kiralama" },
    { baslik: "Eklemli Platformlar", metin: "Hat, tesisat ve yapı engellerinin üzerinden güvenli yatay erişim.", gorsel: "/media/eklemli-platform.png", slug: "eklemli-ve-teleskopik-platform-kiralama" },
    { baslik: "Teleskopik Platformlar", metin: "Silo, baca ve yüksek cephelerde uzun erişim gerektiren işler.", gorsel: "/media/blog/dikey-personel-yukseltici-arti-platform-makine-parki.jpg", slug: "eklemli-ve-teleskopik-platform-kiralama" },
];

function Cerceve({ site, aktif = "", children }: Parameters<TemaModulu["Cerceve"]>[0]) {
    const nav = [["/", "Ana Sayfa"], ["/urunler", "Makine Parkuru"], ["/hakkimizda", "Hakkımızda"], ["/blog", "Blog"], ["/iletisim", "İletişim"]];
    return <div className="min-h-screen overflow-x-hidden bg-[#f7f9fb] text-[#191c1e] font-['Inter']">
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Montserrat:wght@600;700;800&display=swap" />
        <header className="sticky top-0 z-50 border-b border-white/10 bg-[#020617]/95 text-white backdrop-blur-md">
            <div className="mx-auto flex max-w-[1280px] items-center justify-between px-4 py-4 md:px-6">
                <a href="/" className="flex items-center gap-3"><Image src="/media/logo/logo.png" alt={`${site.h1} logosu`} width={150} height={40} className="h-9 w-auto object-contain" /><span className="hidden font-['Montserrat'] text-[18px] font-bold sm:block">Kütahya Platform</span></a>
                <nav className="hidden items-center gap-1 lg:flex">{nav.map(([href, etiket]) => <a key={href} href={href} className={`rounded-[2px] px-3 py-2 text-[14px] font-semibold tracking-[0.05em] transition-colors ${aktif === href ? "bg-[#1D4ED8] text-white" : "text-white hover:text-[#67E8F9]"}`}>{etiket}</a>)}</nav>
                <a href={`tel:${site.telefon}`} className="flex items-center gap-2 rounded-[2px] bg-[#67E8F9] px-4 py-3 text-[14px] font-bold text-[#020617]"><Ikon ad="telefon" className="h-4 w-4" /><span className="hidden md:inline">{site.telefonGosterim}</span><span className="md:hidden">Ara</span></a>
            </div>
        </header>
        <main>{children}</main>
        <footer className="bg-[#020617] px-6 py-14 text-white">
            <div className="mx-auto grid max-w-[1280px] gap-10 md:grid-cols-3">
                <div><h2 className="font-['Montserrat'] text-[24px] font-bold">Kütahya Platform</h2><p className="mt-4 text-[14px] leading-5 text-[#c0c6de]">{site.uzmanlik} için doğru makine ve yazılı teklif planlaması.</p></div>
                <div><h3 className="font-['Montserrat'] text-[20px] font-semibold text-[#67E8F9]">Hızlı Menü</h3><div className="mt-4 grid grid-cols-2 gap-3 text-[14px]">{nav.slice(1).map(([h, e]) => <a key={h} href={h} className="hover:text-[#67E8F9]">{e}</a>)}<a href={site.anaSite.url} className="hover:text-[#67E8F9]">{site.anaSite.ad}</a></div></div>
                <div><h3 className="font-['Montserrat'] text-[20px] font-semibold text-[#67E8F9]">İletişim</h3><a href={`tel:${site.telefon}`} className="mt-4 flex gap-2"><Ikon ad="telefon" />{site.telefonGosterim}</a><a href={`mailto:${site.eposta}`} className="mt-3 flex gap-2 break-all"><Ikon ad="posta" />{site.eposta}</a></div>
            </div>
        </footer>
        <a href={`tel:${site.telefon}`} aria-label="Kütahya Platform'u ara" className="fixed bottom-6 right-6 z-40 flex h-14 w-14 items-center justify-center rounded-[8px] bg-[#67E8F9] text-[#020617] shadow-xl"><Ikon ad="telefon" /></a>
    </div>;
}

function AnaSayfa({ site }: { site: SiteIcerik }) {
    const yazilar = hostBloglari(site.host).slice(0, 3);
    return <>
        <section className="relative flex h-[80vh] min-h-[600px] items-center overflow-hidden bg-[#020617]">
            <Image src="/media/saha-hero.png" alt="Kütahya platform kiralama saha çalışması" fill priority sizes="100vw" className="object-cover" />
            <div className="absolute inset-0 bg-gradient-to-r from-[#020617]/95 via-[#020617]/75 to-[#020617]/20" />
            <div className="relative mx-auto w-full max-w-[1280px] px-4 md:px-12">
                <div className="max-w-[680px] text-white"><span className="mb-4 block text-[12px] font-semibold tracking-[0.05em] text-[#67E8F9]">KÜTAHYA&apos;DA ENDÜSTRİYEL ÇÖZÜMLER</span><h1 className="mb-6 font-['Montserrat'] text-[32px] font-bold leading-[40px] tracking-[-0.01em] md:text-[48px] md:leading-[56px] md:tracking-[-0.02em]">{site.h1}<br /><span className="text-[#67E8F9]">Güvenli. Hızlı. Profesyonel.</span></h1><p className="mb-8 max-w-xl text-[18px] leading-[28px] text-white/80">{site.paragraflar[0]}</p><div className="flex flex-wrap gap-4"><a href="/iletisim" className="flex items-center gap-2 rounded-[2px] bg-[#67E8F9] px-8 py-4 text-[14px] font-semibold tracking-[0.05em] text-[#020617]">Hemen Teklif Al <Ikon ad="ok" /></a><a href="/urunler" className="rounded-[2px] border border-white px-8 py-4 text-[14px] font-semibold tracking-[0.05em] text-white">Makine Parkurunu İncele</a></div></div>
            </div>
        </section>
        <section className="bg-[#f7f9fb] px-4 py-12 md:px-12"><div className="mx-auto max-w-[1280px]"><h2 className="mb-12 text-center font-['Montserrat'] text-[32px] font-bold leading-[40px] text-[#020617]">Kiralama Çözümlerimiz</h2><div className="grid gap-6 md:grid-cols-3">{urunler.map((u) => <article key={u.baslik} className="group overflow-hidden rounded-[8px] border border-[#c6c6cd] bg-white"><div className="relative h-64 overflow-hidden"><Image src={u.gorsel} alt={u.baslik} fill sizes="(max-width:768px) 100vw, 33vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /></div><div className="p-6"><h3 className="mb-2 flex items-center justify-between font-['Montserrat'] text-[20px] font-semibold leading-[28px] text-[#020617]">{u.baslik}<Ikon ad="ok" className="h-5 w-5 text-[#1D4ED8]" /></h3><p className="text-[14px] leading-[20px] text-[#46464c]">{u.metin}</p></div></article>)}</div></div></section>
        <section className="bg-[#020617] px-4 py-12 text-white md:px-12"><div className="mx-auto grid max-w-[1280px] items-center gap-12 md:grid-cols-2"><div><h2 className="mb-6 font-['Montserrat'] text-[32px] font-bold leading-[40px]">Güven ve Tecrübenin Adresi</h2><p className="mb-6 text-[18px] leading-[28px] text-white/80">{site.paragraflar[1]}</p><div className="grid grid-cols-2 gap-6">{[["10+", "Yıllık Tecrübe"], ["50+", "Makine Seçeneği"], ["7/24", "Teknik Destek"], ["%100", "Müşteri Memnuniyeti"]].map(([s, e]) => <div key={e}><div className="font-['Montserrat'] text-[32px] font-bold text-[#67E8F9]">{s}</div><div className="text-[14px] text-white/70">{e}</div></div>)}</div><a href="/hakkimizda" className="mt-8 inline-flex rounded-[2px] border border-[#67E8F9] px-6 py-3 text-[14px] font-semibold tracking-[0.05em] text-[#67E8F9]">Bizi Daha Yakından Tanıyın</a></div><div className="relative min-h-[420px] overflow-hidden rounded-[8px]"><Image src="/media/guvenli-calisma.png" alt="Güvenli yüksekte çalışma" fill sizes="50vw" className="object-cover" /></div></div></section>
        <section className="bg-[#f7f9fb] px-4 py-12 md:px-12"><div className="mx-auto max-w-[1280px]"><div className="mb-10 text-center"><h2 className="mb-4 font-['Montserrat'] text-[32px] font-bold leading-[40px] text-[#020617]">Sektörel Bilgiler & Rehberler</h2><p className="mx-auto max-w-2xl text-[16px] leading-[24px] text-[#46464c]">İş makineleri dünyasındaki son gelişmeler, güvenlik standartları ve verimlilik ipuçları.</p></div><div className="grid gap-6 md:grid-cols-3">{yazilar.map((y) => <article key={y.slug} className="group flex flex-col overflow-hidden rounded-[8px] border border-[#c6c6cd] bg-white"><div className="relative h-48"><Image src={y.gorsel} alt={y.gorselAlt} fill sizes="33vw" className="object-cover" /></div><div className="flex flex-1 flex-col p-6"><span className="mb-2 text-[12px] font-medium text-[#1D4ED8]">{y.kategori}</span><h3 className="mb-3 font-['Montserrat'] text-[20px] font-semibold leading-[28px] text-[#020617]">{y.baslik}</h3><p className="mb-4 line-clamp-3 flex-1 text-[14px] leading-[20px] text-[#46464c]">{y.ozet}</p><a href={`/blog/${y.slug}`} className="flex items-center gap-1 text-[14px] font-semibold text-[#1D4ED8]">Devamını Oku <Ikon ad="ok" className="h-4 w-4" /></a></div></article>)}</div><div className="mt-10 text-center"><a href="/blog" className="inline-flex rounded-[2px] bg-[#020617] px-8 py-4 text-[14px] font-semibold tracking-[0.05em] text-white">Tüm Yazıları Gör</a></div></div></section>
    </>;
}

function Hakkimizda({ site }: { site: SiteIcerik }) {
    return <div className="mx-auto flex max-w-[1280px] flex-col gap-16 px-4 py-12 md:px-12"><section className="grid items-center gap-6 md:grid-cols-2"><div><h1 className="font-['Montserrat'] text-[32px] font-bold leading-[40px] text-[#020617] md:text-[48px] md:leading-[56px]">Güvenilir Erişim,<br /><span className="text-[#1D4ED8]">Planlı Operasyon.</span></h1><p className="mt-6 max-w-prose text-[18px] leading-[28px] text-[#46464c]">{site.paragraflar[0]}</p></div><div className="relative h-[400px] overflow-hidden rounded-[8px]"><Image src="/media/guvenli-calisma.png" alt="Kütahya Platform ekibi" fill sizes="50vw" className="object-cover" /></div></section><section className="grid gap-6 md:grid-cols-3"><div><h2 className="mb-4 font-['Montserrat'] text-[32px] font-bold text-[#020617]">Değerlerimiz</h2><p className="leading-6 text-[#46464c]">{site.paragraflar[1]}</p></div>{["Misyonumuz", "Vizyonumuz"].map((b, i) => <article key={b} className="rounded-[8px] bg-[#f2f4f6] p-8"><h3 className="font-['Montserrat'] text-[20px] font-semibold text-[#020617]">{b}</h3><p className="mt-4 text-[14px] leading-5 text-[#46464c]">{site.hizmetler[i]}</p></article>)}</section><section className="rounded-[8px] bg-[#020617] p-8 text-white md:p-12"><div className="text-center"><h2 className="font-['Montserrat'] text-[32px] font-bold">Neden Bizi Tercih Etmelisiniz?</h2><p className="mx-auto mt-4 max-w-2xl text-white/80">{site.paragraflar[2]}</p></div><div className="mt-10 grid gap-8 md:grid-cols-3">{site.hizmetler.slice(0, 3).map((h, i) => <article key={h} className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#1D4ED8] text-[#67E8F9]"><Ikon ad="onay" className="h-8 w-8" /></div><h3 className="mt-4 font-['Montserrat'] text-[20px] font-semibold">{["Güvenli Ekipman", "Hızlı Sevkiyat", "Uzman Destek"][i]}</h3><p className="mt-2 text-[14px] text-white/80">{h}</p></article>)}</div></section><section><h2 className="border-b border-[#c6c6cd] pb-4 font-['Montserrat'] text-[32px] font-bold text-[#020617]">Gelişim Sürecimiz</h2><div className="mt-8 space-y-8">{["Temellerin Atılması", "Platform Yatırımları", "Bölgesel Güç"].map((b, i) => <article key={b} className="grid gap-4 md:grid-cols-[120px_1fr]"><span className="font-['Montserrat'] text-[24px] font-bold text-[#1D4ED8]">{["2014", "2019", "Bugün"][i]}</span><div><h3 className="font-['Montserrat'] text-[20px] font-semibold text-[#020617]">{b}</h3><p className="mt-2 text-[14px] leading-5 text-[#46464c]">{site.hizmetler[i + 1] ?? site.uzmanlik}</p></div></article>)}</div></section></div>;
}

function Urunler() {
    const teknik = [["12 m", "Çalışma Yüksekliği", "300 kg", "Kapasite"], ["16 m", "Çalışma Yüksekliği", "230 kg", "Kapasite"], ["32 m", "Azami Erişim", "230 kg", "Kapasite"]];
    return <div className="mx-auto max-w-[1280px] px-4 py-12 md:px-12"><section className="mb-12"><h1 className="font-['Montserrat'] text-[32px] font-bold leading-[40px] text-[#020617] md:text-[48px] md:leading-[56px]">Makine Parkuru</h1><p className="mt-3 max-w-2xl text-[18px] leading-[28px] text-[#46464c]">Modern, bakımlı ve periyodik kontrolleri yapılmış ekipman seçenekleri.</p><div className="mt-8 flex flex-wrap gap-3">{["Tümü", "Makaslı Platform", "Eklemli Platform", "Teleskopik"].map((x, i) => <span key={x} className={`rounded-full border px-4 py-2 text-[14px] font-semibold ${i === 0 ? "border-[#1D4ED8] bg-[#f1f5f9] text-[#1D4ED8]" : "border-[#c6c6cd] bg-white text-[#46464c]"}`}>{x}</span>)}</div></section><section className="grid gap-6 md:grid-cols-3">{urunler.map((u, i) => <article key={u.baslik} className="group flex flex-col rounded-[2px] border border-[#c6c6cd] bg-[#f1f5f9] transition-all hover:border-2 hover:border-[#1D4ED8]"><div className="relative h-60 overflow-hidden"><Image src={u.gorsel} alt={u.baslik} fill sizes="33vw" className="object-cover" /><span className="absolute left-4 top-4 rounded-[2px] bg-[#BEF264] px-3 py-1 text-[12px] font-semibold text-[#020617]">KİRALAMAYA UYGUN</span></div><div className="flex flex-1 flex-col p-6"><h2 className="mb-4 font-['Montserrat'] text-[20px] font-semibold text-[#020617]">{u.baslik}</h2><div className="mb-6 grid grid-cols-2 gap-4">{teknik[i].reduce<{ v: string; e: string }[]>((a, x, n, arr) => n % 2 === 0 ? [...a, { v: x, e: arr[n + 1] }] : a, []).map((t) => <div key={t.e}><div className="font-['Montserrat'] text-[20px] font-semibold text-[#020617]">{t.v}</div><div className="text-[12px] text-[#46464c]">{t.e}</div></div>)}</div><p className="mb-6 flex-1 text-[14px] leading-5 text-[#46464c]">{u.metin}</p><a href={`/${u.slug}`} className="flex w-full items-center justify-center gap-2 rounded-[2px] bg-[#020617] py-3 text-[14px] font-semibold text-white">Detayları İncele <Ikon ad="ok" /></a></div></article>)}</section><section className="mt-12 rounded-[4px] border border-[#c6c6cd] bg-[#f1f5f9] p-8 md:p-12"><h3 className="border-b border-[#c6c6cd] pb-4 font-['Montserrat'] text-[24px] font-semibold text-[#020617]">Doğru Makineyi Nasıl Seçersiniz?</h3><div className="mt-6 grid gap-5 md:grid-cols-3">{["Çalışma yüksekliğini ve yatay erişimi ölçün.", "Zemin, kapı ve koridor koşullarını paylaşın.", "Tarih ve saha giriş şartlarını netleştirin."].map((x) => <p key={x} className="flex gap-3"><span className="text-[#1D4ED8]"><Ikon ad="onay" /></span>{x}</p>)}</div></section></div>;
}

function Iletisim({ site }: { site: SiteIcerik }) {
    const bolgeler = site.bolge.split(",").map((b) => b.trim());
    const sss = [["Kiralama süreci nasıl işliyor?", "İşin yüksekliği, zemin, tarih ve adres bilgileri alınır; uygun makine ve sevkiyat kapsamı yazılı teklifle sunulur."], ["Makinelerin bakımları düzenli yapılıyor mu?", "Sunulacak makinenin güncel bakım ve periyodik kontrol evrakı teklif ve teslimat aşamasında doğrulanır."], ["Operatörlü kiralama yapıyor musunuz?", "Operatör gereksinimi saha ve makine sınıfına göre değerlendirilir; kapsam yazılı teklifte açıkça belirtilir."]];
    return <><section className="mx-auto max-w-[1280px] px-4 py-12 md:px-12"><h1 className="font-['Montserrat'] text-[32px] font-bold text-[#020617] md:text-[48px]">İletişim</h1><p className="mt-4 max-w-3xl text-[18px] leading-7 text-[#46464c]">Ağır iş makineleri kiralama ihtiyaçlarınız için bize ulaşın. Uzman ekibimiz size en uygun çözümü sunmak için hazır.</p><div className="mt-10 grid gap-10 lg:grid-cols-[1.4fr_1fr]"><div className="relative overflow-hidden rounded-[8px] bg-white p-8 shadow-[0_10px_30px_rgba(2,6,23,0.08)]"><div className="absolute -right-24 -top-24 h-64 w-64 rounded-full bg-[#f2f4f6] opacity-50 blur-3xl" /><h2 className="relative font-['Montserrat'] text-[24px] font-semibold text-[#020617]">Bize Mesaj Gönderin</h2><div className="relative mt-6"><TemaForm eposta={site.eposta} konu={`Kütahya Platform Teklif Talebi — ${site.h1}`} opsiyonlar={bolgeler} cls={{etiket:"mb-2 block text-[14px] font-semibold text-[#020617]",alan:"w-full rounded-[2px] border border-[#c6c6cd] bg-[#f7f9fb] p-3 outline-none focus:border-[#1D4ED8]",buton:"w-full rounded-[2px] bg-[#020617] px-8 py-4 font-bold text-white hover:bg-[#1D4ED8]",izgara:"grid gap-5 md:grid-cols-2"}} /></div></div><aside className="rounded-[8px] bg-[#f2f4f6] p-8"><h2 className="font-['Montserrat'] text-[20px] font-semibold text-[#020617]">İletişim Bilgileri</h2><a href={`tel:${site.telefon}`} className="mt-8 flex gap-4"><span className="text-[#1D4ED8]"><Ikon ad="telefon" /></span><span><small className="block uppercase tracking-wider text-[#46464c]">Telefon</small>{site.telefonGosterim}</span></a><a href={`mailto:${site.eposta}`} className="mt-6 flex gap-4 break-all"><span className="text-[#1D4ED8]"><Ikon ad="posta" /></span><span><small className="block uppercase tracking-wider text-[#46464c]">E-posta</small>{site.eposta}</span></a><div className="mt-6 flex gap-4"><span className="text-[#1D4ED8]"><Ikon ad="konum" /></span><span><small className="block uppercase tracking-wider text-[#46464c]">Hizmet Bölgesi</small>{site.bolge}</span></div></aside></div></section><section className="bg-[#f2f4f6] px-4 py-12 md:px-12"><div className="mx-auto max-w-[960px]"><h2 className="text-center font-['Montserrat'] text-[32px] font-bold text-[#020617]">Sıkça Sorulan Sorular</h2><p className="mx-auto mt-3 max-w-2xl text-center text-[#46464c]">Kiralama süreçlerimiz ve hizmetlerimiz hakkında merak edilen temel sorular.</p><div className="mt-10 space-y-4">{sss.map(([s, c]) => <article key={s} className="rounded-[8px] border border-[#c6c6cd] bg-white p-6"><h3 className="font-['Montserrat'] text-[20px] font-semibold text-[#191c1e]">{s}</h3><p className="mt-3 leading-6 text-[#46464c]">{c}</p></article>)}</div></div></section></>;
}

function BlogListe({ site }: { site: SiteIcerik }) {
    const yazilar = hostBloglari(site.host);
    const kategoriler = [...new Set(yazilar.map((y) => y.kategori))];
    return <><section className="relative overflow-hidden border-b border-[#c6c6cd] bg-[#f1f5f9] px-4 py-12 md:px-12"><div className="absolute -right-24 -top-24 h-64 w-64 rounded-full bg-[#67E8F9]/20 blur-3xl" /><div className="relative mx-auto max-w-[1280px]"><span className="mb-4 block h-1 w-16 bg-[#1D4ED8]" /><h1 className="font-['Montserrat'] text-[32px] font-bold uppercase text-[#020617] md:text-[48px]">Eğitici Blog</h1><p className="mt-3 max-w-2xl text-[18px] leading-7 text-[#46464c]">Endüstriyel ekipman kiralama, iş güvenliği standartları ve makine bakımına dair uzman görüşleri, güncel rehberler ve sektörel analizler.</p></div></section><section className="mx-auto flex max-w-[1280px] flex-col gap-6 px-4 py-12 md:px-12 lg:flex-row"><div className="grid flex-1 gap-6 md:grid-cols-2">{yazilar.map((y) => <article key={y.slug} className="group flex h-full flex-col overflow-hidden rounded-[2px] border border-[#c6c6cd] bg-white"><div className="relative h-56"><Image src={y.gorsel} alt={y.gorselAlt} fill sizes="33vw" className="object-cover" /><span className="absolute left-4 top-4 rounded-[2px] bg-[#67E8F9] px-3 py-1 text-[12px] font-medium text-[#020617]">{y.kategori}</span></div><div className="flex flex-1 flex-col p-6"><span className="text-[12px] text-[#46464c]">{y.okuma} dakika okuma</span><h2 className="mt-2 font-['Montserrat'] text-[20px] font-semibold text-[#020617]">{y.baslik}</h2><p className="mt-3 line-clamp-3 flex-1 text-[14px] leading-5 text-[#46464c]">{y.ozet}</p><a href={`/blog/${y.slug}`} className="mt-5 flex items-center gap-2 text-[14px] font-semibold text-[#1D4ED8]">Devamını Oku <Ikon ad="ok" className="h-4 w-4" /></a></div></article>)}</div><aside className="w-full space-y-6 lg:w-80"><div className="rounded-[2px] bg-[#f2f4f6] p-6"><h3 className="border-b border-[#c6c6cd] pb-2 font-['Montserrat'] text-[20px] font-semibold text-[#020617]">Kategoriler</h3><div className="mt-4 space-y-3">{kategoriler.map((k) => <div key={k} className="flex justify-between text-[14px]"><span>{k}</span><span className="text-[#1D4ED8]">{yazilar.filter((y) => y.kategori === k).length}</span></div>)}</div></div><div className="rounded-[2px] bg-[#020617] p-6 text-white"><h3 className="font-['Montserrat'] text-[20px] font-semibold">Teklif İhtiyacınız mı var?</h3><p className="mt-3 text-[14px] leading-5 text-white/75">Saha bilgilerinizi paylaşın, uygun makine sınıfını birlikte belirleyelim.</p><a href="/iletisim" className="mt-5 inline-flex rounded-[2px] bg-[#67E8F9] px-5 py-3 text-[14px] font-semibold text-[#020617]">Bize Ulaşın</a></div></aside></section></>;
}

export const kutahyaTema: TemaModulu = {
    Cerceve,
    AnaSayfa,
    sayfalar: { hakkimizda: Hakkimizda, iletisim: Iletisim, urunler: Urunler },
    BlogListe,
};
